
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "modpack"
  name = "fettlol-beta"
  description = "The 1.18.1 beta branch of the Fettlol Modpack. Might not be stable."
  version = "1.0.80"
  platform = "fabric"
  license = "MIT"
  author = "Breki Tomasson <breki.tomasson@gmail.com>"

# These are global requirements
[requirements]
  minecraft = "1.18.1"
  fabricLoader = "^0.12.6"

[dependencies]
  additional-additions = "https://cdn.modrinth.com/data/R4TvILfj/versions/3.0.1/AdditionalAdditions-3.0.1.jar"
  adorn = "https://cdn.modrinth.com/data/E6FUtRJh/versions/3.3.1-fabric/Adorn-3.3.1%2B1.18.1-fabric.jar"
  alaska-nativecraft = "https://cdn.modrinth.com/data/iFnEtHsI/versions/1.4.2/alaskanativecraft-1.4.2.jar"
  appleskin = "^2.2.0+1.18.mpkg.1"
  applied-energistics = "https://cdn.modrinth.com/data/XxWD5pD3/versions/fabric-10.1.0-beta.1/appliedenergistics2-10.1.0-beta.1.jar"
  architectury = "^3.4.9+mpkg.1"
  axesareweapons = "^1.5.1"
  bedspreads = "https://brekitomasson.com/fettlol/mods/1.18/bedspreads-fabric-1.5.0-1.18.jar"
  biome-makeover = "https://brekitomasson.com/fettlol/mods/1.18/biomemakeover-FABRIC-1.18.1-1.4.1.jar"
  blast = "https://brekitomasson.com/fettlol/mods/1.18/blast-1.8.2.jar"
  blur = "^2.4.1+mpkg.1"
  branders-spawnermod = "https://brekitomasson.com/fettlol/mods/1.18/fabric-branders-spawnermod-1.18-1.1.2.jar"
  candlestick = "https://brekitomasson.com/fettlol/mods/1.18/Candlestick-1.1.2.jar"
  caracal-mob = "^1.3.3+1.18.mpkg.1"
  chat-heads = "^0.5.1+mpkg.1"
  cloth-config = "^6.1.48+mpkg.1"
  coloredslime = "^1.3.1"
  concrete-plus = "https://brekitomasson.com/fettlol/mods/1.18/pandamc_concreteplus-1.9.2.jar"
  continuity = "https://cdn.modrinth.com/data/1IjD5062/versions/1.0.3+1.18/continuity-1.0.3+1.18.jar"
  copper-equipment = "https://cdn.modrinth.com/data/cDfJDREb/versions/1.8.1/CopperEquipment-Fabric1.18.1-1.8.1.jar"
  croptopia = "https://brekitomasson.com/fettlol/mods/1.18/Croptopia-1.18-FABRIC-1.8.0.jar"
  damagetilt = "^0.1.2+1.18.mpkg.1"
  dank-storage = "https://brekitomasson.com/fettlol/mods/1.18/dankstorage-1.18.1-3.5.jar"
  dark-loading-screen = "^1.6.5+mpkg.1"
  dawn = "https://cdn.modrinth.com/data/meZK2DCX/versions/3.2.0/dawn-3.2.0.jar"
  deepslate-cutting = "https://cdn.modrinth.com/data/IiuFShHs/versions/DeepslateCutting%201.3.0/deepslatecutting-1.18-1.3.0.jar"
  dense-ores = "https://cdn.modrinth.com/data/mJq5ykOP/versions/1.2.1+1.18.1/denseores-1.2.1+1.18.1.jar"
  discerning-furnace = "https://cdn.modrinth.com/data/G3Nz6HN4/versions/1.0.5+MC1.18-1.18.1/discerning-furnace-1.0.5+MC1.18-1.18.1.jar"
  ducts = "https://brekitomasson.com/fettlol/mods/1.18/ducts-1.1.6.jar"
  dungeons-arise = "https://cdn.modrinth.com/data/8DfbfASn/versions/2.1.49b/DungeonsArise-1.18.1-2.1.49b-fabric-beta.jar"
  dye-all-the-things = "https://brekitomasson.com/fettlol/mods/1.18/DyeAllTheThings-1.1.jar"
  earth2java = "^1.7.4+1.18.mpkg.1"
  eating-animation = "https://brekitomasson.com/fettlol/mods/1.18/eating-animation-1.2.jar"
  eldritch-mobs = "https://brekitomasson.com/fettlol/mods/1.18/eldritch-mobs-1.10.2.jar"
  emotecraft = "https://cdn.modrinth.com/data/pZ2wrerK/versions/2.1-SNAPSHOT-build.10-fabric/emotecraft-for-MC1.18.1-2.1-SNAPSHOT-build.10-fabric.jar"
  extra-generators = "https://cdn.modrinth.com/data/VXtwLg17/versions/1.1.1-BETA+1.18/extra-generators-1.1.1-BETA+1.18.jar"
  fabric = "*"
  fabric-language-kotlin = "https://cdn.modrinth.com/data/Ha28R6CL/versions/1.7.1+kotlin.1.6.10/fabric-language-kotlin-1.7.1+kotlin.1.6.10.jar"
  fabricated-chisel = "https://cdn.modrinth.com/data/4KWv7wbN/versions/1.4.3/chisel-1.4.3+1.18.1.jar"
  fallingleaves = "^1.9.0"
  feature_nbt_deadlock_be_gone = "https://cdn.modrinth.com/data/HMNV4z01/versions/1.0.1+1.18.1_fabric/feature_nbt_deadlock_be_gone_fabric-1.0.1+1.18.1.jar"
  fettlol-utilmod = "^1.3.2"
  flonters = "https://brekitomasson.com/fettlol/mods/1.18/Flonters-1.3.0+1.18.1.jar"
  geckolib = "^3.0.23+1.18.mpkg.1"
  go-fish = "^1.4.1+mpkg.1"
  grizzlybear-mob = "https://brekitomasson.com/fettlol/mods/1.18/grizzlybear-1.18-1.2.2.jar"
  guardians-galore = "https://brekitomasson.com/fettlol/mods/1.18/GuardiansGalore-1.18-3.0.jar"
  horsestats-vanilla = "https://cdn.modrinth.com/data/l4qoXLzx/versions/4.1.10/horse-stats-vanilla-4.1.10.jar"
  hwyla-horseinfo = "https://brekitomasson.com/fettlol/mods/1.18/hwyla-addon-horseinfo-0.4.0-1.18.jar"
  illuminations = "https://brekitomasson.com/fettlol/mods/1.18/illuminations-1.10.2.jar"
  indium = "https://cdn.modrinth.com/data/Orvt0mRa/versions/1.0.2-alpha2+mc1.18.1/indium-1.0.2-alpha2+mc1.18.1.jar"
  infinity-water-bucket = "https://cdn.modrinth.com/data/nNMXZUPi/versions/1.18.1-2.0.0/Infinity-Water-Bucket-Fabric-1.18.1-2.0.0.jar"
  inventory-profiles = "https://cdn.modrinth.com/data/O7RBXm3n/versions/fabric-1.18.1-1.3.1/InventoryProfilesNext-fabric-1.18-1.3.1.jar"
  keepheadnames = "^1.5.1+1.18"
  krypton = "^0.1.6+mpkg.1"
  lamb-better-grass = "https://cdn.modrinth.com/data/2Uev7LdA/versions/1.2.2+1.17/lambdabettergrass-1.2.2+1.17.jar"
  lamb-dynamic-lights = "https://cdn.modrinth.com/data/yBW8D80W/versions/2.1.0+1.17/lambdynamiclights-2.1.0+1.17.jar"
  leaves-us-in-peace = "https://cdn.modrinth.com/data/IIpWIe1o/versions/1.0.3+MC1.18-1.18.1/leaves-us-in-peace-1.0.3%2BMC1.18-1.18.1.jar"
  lifts = "^1.4.0-BETA+1.18.mpkg.1"
  lithium = ">=0.7.7+mpkg.1"
  mcda = "https://brekitomasson.com/fettlol/mods/1.18/mcda-1.9.0.jar"
  mcdw = "https://brekitomasson.com/fettlol/mods/1.18/mcdw-4.0.2.jar"
  mcf-easyfeed = "^1.3.0+1.18.mpkg.1"
  midas-hunger = "https://cdn.modrinth.com/data/abF2tqnb/versions/2.0.0+1.18.1/midas-hunger-2.0.0+1.18.1.jar"
  modmenu = "^3.0.0+mpkg.1"
  more-axolotl-variants = "https://brekitomasson.com/fettlol/mods/1.18/mavm-fabric-1.18.1-1.0.7a.jar"
  mythic-mounts = "https://brekitomasson.com/fettlol/mods/1.18/mythic-mounts-3.0.jar"
  no_null_processors = "https://brekitomasson.com/fettlol/mods/1.18/no_null_processors_fabric-2.0.1+1.18.1.jar"
  not-enough-animations = "https://brekitomasson.com/fettlol/mods/1.18/notenoughanimations-fabric-1.4.0-mc1.18-pre1.jar"
  notenoughcrashes = "^4.1.3+1.18.mpkg.2"
  npc-variety = "https://brekitomasson.com/fettlol/mods/1.18/npc-variety-1.18-2.2.2.jar"
  numismatic-overhaul = "https://cdn.modrinth.com/data/ZXm8hVxN/versions/0.1.8+1.18/numismatic-overhaul-0.1.8%2B1.18.jar"
  okzoomer = "^5.0.0-beta.3+1.17.1.mpkg.1"
  ottercraft = "https://brekitomasson.com/fettlol/mods/1.18/Ottercraft-fabric-1.18-1.1.10.jar"
  owo = "https://cdn.modrinth.com/data/ccKDOlHs/versions/0.5.1+1.18/owo-lib-0.5.1+1.18.jar"
  perfectaccuracy = "^1.2.0"
  promenade = "https://cdn.modrinth.com/data/GuE5FpvB/versions/2.5.0/promenade-2.5.0.jar"
  repurposed-structures = "https://cdn.modrinth.com/data/muf0XoRe/versions/3.3.9+1.18.1/repurposed_structures_fabric-3.3.9%2B1.18.1.jar"
  reroll = "^1.3.0"
  ring-of-attraction = "https://brekitomasson.com/fettlol/mods/1.18/RingOfAttraction-Fabric-1.18.1-1.2.20.jar"
  roughlyenoughitems = "^7.0.343+mpkg.1"
  rpg-stats = "https://cdn.modrinth.com/data/8RtckdKf/versions/4.3.4+1.18.1/rpgstats-4.3.4+1.18.1.jar"
  simple-voice-chat = "https://cdn.modrinth.com/data/9eGKb6K1/versions/fabric-1.18.1-2.2.21/voicechat-fabric-1.18.1-2.2.21.jar"
  skin-layers = "https://brekitomasson.com/fettlol/mods/1.18/3dSkinLayers-Fabric-1.3.1.jar"
  slimy-floor = "https://brekitomasson.com/fettlol/mods/1.18/slimyfloor-1.18-1.2.2.jar"
  sodium = "https://cdn.modrinth.com/data/AANobbMI/versions/mc1.18.1-0.4.0-alpha6/sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar"
  sodium-extra = "https://cdn.modrinth.com/data/PtjYWJkn/versions/mc1.18.1-0.3.9/sodium-extra-mc1.18.1-0.3.9.jar"
  spark = "https://cdn.modrinth.com/data/l6YH9Als/versions/1.7.2-fabric/spark-fabric.jar"
  starlight = "^1.0.1+mpkg.1"
  taxfreelevels = "^1.3.0"
  techreborn = "https://brekitomasson.com/fettlol/mods/1.18/TechReborn-5.1.0-beta.7.jar"
  the-graveyard = "https://brekitomasson.com/fettlol/mods/1.18/The_Graveyard_1.2_(FABRIC)_for_1.18.1.jar"
  true-darkness = "https://cdn.modrinth.com/data/Ja7zPEaN/versions/fabric-mc118-2.0.89/darkness-fabric-mc118-2.0.89.jar"
  villager-names = "https://brekitomasson.com/fettlol/mods/1.18/villagernames-1.18-2.0.2.jar"
  waystones = "^2.4.0+mpkg.1"
  wolves-with-armor = "https://brekitomasson.com/fettlol/mods/1.18/wolves-with-armor-1.7.0-1.18.jar"
  wthit = "^4.3.1+mpkg.1"
  xaeros-minimap = "https://brekitomasson.com/fettlol/mods/1.18/Xaeros_Minimap_21.23.0_Fabric_1.18.jar"
  xaeros-worldmap = "https://brekitomasson.com/fettlol/mods/1.18/XaerosWorldMap_1.19.0_Fabric_1.18.jar"

[dev]
