
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "modpack"
  name = "fettlol-beta"
  description = "The beta branch of the Fettlol Modpack. Might not be stable."
  version = "1.0.31"
  platform = "fabric"
  license = "MIT"
  author = "Breki Tomasson <breki.tomasson@gmail.com>"

# These are global requirements
[requirements]
  minecraft = "1.17.1"
  fabricLoader = "*"

[dependencies]
  adorn = "^2.1.3-0.mpkg.1"
  advancements-debug = "https://www.brekitomasson.com/fettlol/mods/1.17.1/advdebug-2.3.0.jar"
  alaska-nativecraft = "https://www.brekitomasson.com/fettlol/mods/1.17.1/alaskanativecraft-1.3.0.jar"
  amecs = "^1.3.4-0.mpkg.1"
  appleskin = "https://www.brekitomasson.com/fettlol/mods/1.17.1/appleskin-fabric-mc1.17-2.1.3.jar"
  architectury = "^2.4.25-0.mpkg.1"
  autopath = "https://www.brekitomasson.com/fettlol/mods/1.17.1/autopath-mc1.17-1.4.3.jar"
  axesareweapons = "https://www.brekitomasson.com/fettlol/mods/1.17.1/AxesAreWeapons-1.3-1.17.jar"
  axolotl-bucket-fix = "^1.1.1"
  bclib = "https://www.brekitomasson.com/fettlol/mods/1.17.1/bclib-0.3.1.jar"
  bedspreads = "https://www.brekitomasson.com/fettlol/mods/1.17.1/bedspreads-fabric-1.4.0-1.17.jar"
  beenfo = "https://www.brekitomasson.com/fettlol/mods/1.17.1/beenfo-1.17.1-fabric0.36.1-1.3.2.jar"
  better-biome-blend = "https://www.brekitomasson.com/fettlol/mods/1.17.1/betterbiomeblend-1.17.0-1.2.3-fabric.jar"
  better-dropped-items = "https://www.brekitomasson.com/fettlol/mods/1.17.1/betterdroppeditems-1.3.0-1.17.jar"
  better-enchanted-books = "https://www.brekitomasson.com/fettlol/mods/1.17.1/better-enchanted-books-1.17-1.2.9.jar"
  better-ping-display = "^1.1.0-1.17.mpkg.1"
  betterend = "https://www.brekitomasson.com/fettlol/mods/1.17.1/better-end-0.11.0-pre.jar"
  betternether = "https://www.brekitomasson.com/fettlol/mods/1.17.1/better-nether-5.1.3.jar"
  blame = "https://www.brekitomasson.com/fettlol/mods/1.17.1/blame-1.17-4.1.0-fabric.jar"
  blur = "https://www.brekitomasson.com/fettlol/mods/1.17.1/Blur-2.2.0-1.17+fabric.jar"
  byg = "https://www.brekitomasson.com/fettlol/mods/1.17.1/byg-1.1.8-BETA.jar"
  candlestick = "https://www.brekitomasson.com/fettlol/mods/1.17.1/Candlestick-1.1.1.jar"
  capes = "https://www.brekitomasson.com/fettlol/mods/1.17.1/capes-1.2.0.jar"
  caracal-mob = "^1.3.1-1.17.mpkg.1"
  charm = "https://www.brekitomasson.com/fettlol/mods/1.17.1/charm-fabric-1.17-3.3.2.jar"
  clear-skies = "https://www.brekitomasson.com/fettlol/mods/1.17.1/clear-skies-mc117-1.5.70.jar"
  cloth-config = "https://www.brekitomasson.com/fettlol/mods/1.17.1/cloth-config-5.0.37-fabric.jar"
  coloredslime = "^1.2.6"
  colorful-azaleas = "https://www.brekitomasson.com/fettlol/mods/1.17.1/Colorful_Azaleas_1.2_for_1.17-1.171.jar"
  compressed = "https://www.brekitomasson.com/fettlol/mods/1.17.1/compressed-fabric-1.3.3.jar"
  concrete-plus = "https://www.brekitomasson.com/fettlol/mods/1.17.1/concrete-plus-1.9.jar"
  copper-beacons = "https://www.brekitomasson.com/fettlol/mods/1.17.1/copper-beacons-1.0.1.jar"
  copper-equipment = "https://www.brekitomasson.com/fettlol/mods/1.17.1/CopperEquipment-Fabric1.17.1-1.4.jar"
  croptopia = "https://www.brekitomasson.com/fettlol/mods/1.17.1/Croptopia-1.17-FABRIC-1.6.0.jar"
  damagetilt = "^0.1.2-1.17.mpkg.1"
  dankstorage = "https://www.brekitomasson.com/fettlol/mods/1.17.1/dankstorage-2.1-1.17.1.jar"
  dark-loading-screen = "^1.6.7-0.mpkg.1"
  defaultsettings = "https://www.brekitomasson.com/fettlol/mods/1.17.1/DefaultSettings-1.17.x-3.0.3.jar"
  dirtnt = "^1.0.0-1.17"
  discerning-furnace = "^1.0.3-0.mpkg.1"
  drip-sounds = "https://www.brekitomasson.com/fettlol/mods/1.17.1/DripSounds-1.17-0.2.2.jar"
  ducts = "https://www.brekitomasson.com/fettlol/mods/1.17.1/ducts-1.1.4.jar"
  earth2java = "^1.7.1-0.mpkg.1+1.17-pre3"
  emotecraft = "https://www.brekitomasson.com/fettlol/mods/1.17.1/emotecraft-for-MC1.17.1-2.1-SNAPSHOT-b692f79-fabric.jar"
  expandedstorage = "https://www.brekitomasson.com/fettlol/mods/1.17.1/expandedstorage-7.0.1+1.17.1.jar"
  extra-generators = "https://www.brekitomasson.com/fettlol/mods/1.17.1/extra-generators-1.0.6-BETA+1.17.jar"
  fabric = "^0.38.0"
  fabric-language-kotlin = "^1.6.2-0.mpkg.3+kotlin.1.5.20"
  fallingleaves = "^1.7.3"
  fallingtree = "https://www.brekitomasson.com/fettlol/mods/1.17.1/FallingTree-1.17.1-2.12.2.jar"
  fettlol-utilmod = "https://www.brekitomasson.com/fettlol/mods/1.17.1/FettLolUtilMod-1.1.2+1.17.jar"
  flonters = "https://www.brekitomasson.com/fettlol/mods/1.17.1/Flonters-1.2.1+1.17.1.jar"
  geckolib = "^3.0.9-1.17.mpkg.3"
  grizzly-bear-mob = "^1.2.0-1.17.mpkg.1"
  guardians-galore = "https://www.brekitomasson.com/fettlol/mods/1.17.1/GuardiansGalore-1.17.1-2.0.jar"
  horseinfo = "https://www.brekitomasson.com/fettlol/mods/1.17.1/hwyla-addon-horseinfo-0.3.0-1.17.jar"
  horsestatsvanilla = "https://www.brekitomasson.com/fettlol/mods/1.17.1/horse-stats-vanilla-4.1.8.jar"
  illuminations = "https://www.brekitomasson.com/fettlol/mods/1.17.1/illuminations-1.6.4.jar"
  infinitywaterbucket = "https://www.brekitomasson.com/fettlol/mods/1.17.1/infinity-water-bucket-1.4-mc1.17-fabric.jar"
  inventory-profiles = "https://www.brekitomasson.com/fettlol/mods/1.17.1/InventoryProfilesNext-fabric-1.17-0.9.0.jar"
  keepheadnames = "^1.3.0"
  krypton = "^0.1.4-0.mpkg.1"
  lambdynamiclights = "https://www.brekitomasson.com/fettlol/mods/1.17.1/lambdynamiclights-2.0.2+1.17.jar"
  lifts = "https://www.brekitomasson.com/fettlol/mods/1.17.1/lifts-1.2-BETA+1.17.jar"
  lightoverlay = "^6.0.0-0.mpkg.pre.5"
  lithium = "https://www.brekitomasson.com/fettlol/mods/1.17.1/lithium-fabric-mc1.17.1-0.7.3.jar"
  lovely-snails = "https://www.brekitomasson.com/fettlol/mods/1.17.1/lovely_snails-1.0.3+1.17.jar"
  mcdunegeonsweapons = "https://www.brekitomasson.com/fettlol/mods/1.17.1/mcdw-3.4.1.jar"
  mcdungeonsarmors = "https://www.brekitomasson.com/fettlol/mods/1.17.1/mcda-1.7.6.jar"
  mcf-easyfeed = "^1.3.0-0.mpkg.1"
  midas-hunger = "https://www.brekitomasson.com/fettlol/mods/1.17.1/midas-hunger-1.4.0.jar"
  miskatonicmysteries = "https://www.brekitomasson.com/fettlol/mods/1.17.1/miskatonicmysteries-0.0.8.jar"
  modmenu = "^2.0.3-0.mpkg.1"
  more-axolotl-variants = "https://www.brekitomasson.com/fettlol/mods/1.17.1/mavm-1.0.3a.jar"
  more-block-bricks = "https://www.brekitomasson.com/fettlol/mods/1.17.1/moreblockbricks-1.3.1-mc-1.17.x.jar"
  moreberries = "https://www.brekitomasson.com/fettlol/mods/1.17.1/moreberries-1.4.2.jar"
  mostructures = "https://www.brekitomasson.com/fettlol/mods/1.17.1/mostructures-1.3.0-pre1-1.17.1-fabric.jar"
  music-discs-galore = "https://www.brekitomasson.com/fettlol/mods/1.17.1/MDG-Fabric-2.0.3.jar"
  nether-chest = "https://www.brekitomasson.com/fettlol/mods/1.17.1/netherchest-mc1.17.x-2.0.jar"
  not-enough-animations = "https://www.brekitomasson.com/fettlol/mods/1.17.1/notenoughanimations-1.3.0.jar"
  notenoughcrashes = "https://www.brekitomasson.com/fettlol/mods/1.17.1/notenoughcrashes-3.4.3+1.17-fabric.jar"
  npcvariety = "https://www.brekitomasson.com/fettlol/mods/1.17.1/npc-variety-1.17.0-2.1.2.jar"
  okzoomer = "https://www.brekitomasson.com/fettlol/mods/1.17.1/okzoomer-5.0.0-beta.2+1.17.jar"
  patchouli = "^1.17.0-0.mpkg.1.54"
  perfectaccuracy = "^1.1.0"
  presence-footsteps = "https://www.brekitomasson.com/fettlol/mods/1.17.1/PresenceFootsteps-r31-1.17-rc1.jar"
  quick-shulker = "https://www.brekitomasson.com/fettlol/mods/1.17.1/quickshulker-1.2.2-1.17.jar"
  repurposed-structures = "https://www.brekitomasson.com/fettlol/mods/1.17.1/repurposed_structures_fabric-2.3.1+1.17.1.jar"
  reroll = "^1.2.1"
  rightclickharvest = "^1.3.0-0.mpkg.1"
  ringofattraction = "https://www.brekitomasson.com/fettlol/mods/1.17.1/RingOfAttraction-Fabric-1.17.1-1.1.13.jar"
  roughlyenoughitems = "^6.0.266-0.mpkg.1-alpha"
  satin-api = "https://www.brekitomasson.com/fettlol/mods/1.17.1/satin-1.6.1.jar"
  searchlight = "https://www.brekitomasson.com/fettlol/mods/1.17.1/searchlight-1.17-fabric-1.1.3.jar"
  seasons = "https://www.brekitomasson.com/fettlol/mods/1.17.1/fabric-seasons-1.2.2-BETA+1.17.jar"
  server-holograms = "https://www.brekitomasson.com/fettlol/mods/1.17.1/holograms-1.3.0+1.17.1.jar"
  servertick = "^1.5.0-0.mpkg.1"
  simple-transport = "https://www.brekitomasson.com/fettlol/mods/1.17.1/simpletransport-1.0.0-1.17.1.jar"
  simply-improved-terrain = "https://www.brekitomasson.com/fettlol/mods/1.17.1/SimplyImprovedTerrain-0.4.0.3-Fabric-1.17.jar"
  slimy-floor = "https://www.brekitomasson.com/fettlol/mods/1.17.1/slimyfloor-1.17.1-1.2.0.jar"
  spark = "https://www.brekitomasson.com/fettlol/mods/1.17.1/spark-fabric.jar"
  spawnermod = "https://www.brekitomasson.com/fettlol/mods/1.17.1/fabric-branders-spawnermod-1.17.1-1.1.2.jar"
  stickyhopper = "https://www.brekitomasson.com/fettlol/mods/1.17.1/stickyhopper-2.3-1.17-1.jar"
  stoneholm = "https://www.brekitomasson.com/fettlol/mods/1.17.1/stoneholm-1.3.jar"
  taxfreelevels = "^1.2.1"
  techreborn = "https://www.brekitomasson.com/fettlol/mods/1.17.1/TechReborn-5.0.6-beta+build.94.jar"
  transliterationlib = "https://www.brekitomasson.com/fettlol/mods/1.17.1/TRansliterationLib-1.1.0.jar"
  traverse = "https://www.brekitomasson.com/fettlol/mods/1.17.1/traverse-4.0.0-beta.2.jar"
  trinkets = "https://www.brekitomasson.com/fettlol/mods/1.17.1/trinkets-3.0.2.jar"
  truedarkness = "^1.6.74-0.mpkg.1"
  trumpet-skeleton = "https://www.brekitomasson.com/fettlol/mods/1.17.1/trumpet-skeleton-fabric-1.1.4.jar"
  untitledduckmod = "^0.3.0-0.mpkg.1"
  villagernames = "https://www.brekitomasson.com/fettlol/mods/1.17.1/villagernames-1.17-2.0.0.jar"
  voicechat = "https://www.brekitomasson.com/fettlol/mods/1.17.1/voicechat-fabric-1.17.1-1.1.7.jar"
  waystones = "^2.0.3-0.mpkg.1"
  winged = "https://www.brekitomasson.com/fettlol/mods/1.17.1/winged-1.17.1-3.0.0.jar"
  wolveswitharmor = "^1.6.0+1.17"
  wthit = "https://www.brekitomasson.com/fettlol/mods/1.17.1/wthit-fabric-3.8.1.jar"
  xaeros-minimap = "https://www.brekitomasson.com/fettlol/mods/1.17.1/Xaeros_Minimap_21.14.1_Fabric_1.17.1.jar"
  xaeros-worldmap = "https://www.brekitomasson.com/fettlol/mods/1.17.1/XaerosWorldMap_1.16.0_Fabric_1.17.1.jar"

[dev]
