
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "modpack"
  name = "fettlol-beta"
  description = "The beta branch of the Fettlol Modpack. Might not be stable."
  version = "1.0.74"
  platform = "fabric"
  license = "MIT"
  author = "Breki Tomasson <breki.tomasson@gmail.com>"

# These are global requirements
[requirements]
  minecraft = "1.17.1"
  fabricLoader = "^0.12.5"

[dependencies]
  additional-additions = "https://www.brekitomasson.com/fettlol/mods/1.17.1/AdditionalAdditions-2.2.0.jar"
  adorn = "^2.1.3-0.mpkg.1"
  advancements-debug = "https://www.brekitomasson.com/fettlol/mods/1.17.1/advdebug-2.3.0.jar"
  alaska-nativecraft = "https://www.brekitomasson.com/fettlol/mods/1.17.1/alaskanativecraft-1.3.1.jar"
  amecs = "^1.3.4-0.mpkg.1"
  appleskin = "https://www.brekitomasson.com/fettlol/mods/1.17.1/appleskin-fabric-mc1.17-2.1.3.jar"
  applied-energistics = "https://www.brekitomasson.com/fettlol/mods/1.17.1/appliedenergistics2-9.0.0-beta.2.jar"
  architectury = "^2.4.25-0.mpkg.1"
  axesareweapons = "https://www.brekitomasson.com/fettlol/mods/1.17.1/AxesAreWeapons-1.3-1.17.jar"
  axolotl-bucket-fix = "^1.1.1"
  battle-towers = "https://www.brekitomasson.com/fettlol/mods/1.17.1/battletowers-3.4.1-1.17.1.jar"
  bedspreads = "https://www.brekitomasson.com/fettlol/mods/1.17.1/bedspreads-fabric-1.4.0-1.17.jar"
  beenfo = "https://www.brekitomasson.com/fettlol/mods/1.17.1/beenfo-1.17.1-fabric0.36.1-1.3.2.jar"
  better-dropped-items = "^1.3.0-0.mpkg.1"
  better-enchanted-books = "^1.2.11-0.mpkg.1"
  better-ping-display = "^1.1.0-1.17.mpkg.1"
  blame = "^4.3.0-0.mpkg.1"
  blast = "https://www.brekitomasson.com/fettlol/mods/1.17.1/blast-1.8.1.jar"
  blur = "https://www.brekitomasson.com/fettlol/mods/1.17.1/blur-2.4.0.jar"
  candlestick = "https://www.brekitomasson.com/fettlol/mods/1.17.1/Candlestick-1.1.1.jar"
  capes = "https://www.brekitomasson.com/fettlol/mods/1.17.1/Capes-1.2.2+1.17.jar"
  caracal-mob = "^1.3.1-1.17.mpkg.1"
  charm = "https://www.brekitomasson.com/fettlol/mods/1.17.1/charm-fabric-1.17-3.3.2.jar"
  chat-heads = "^0.3.1-0.mpkg.1"
  clear-skies = "https://www.brekitomasson.com/fettlol/mods/1.17.1/clear-skies-mc117-1.5.70.jar"
  coloredslime = "^1.2.6"
  colorful-azaleas = "https://www.brekitomasson.com/fettlol/mods/1.17.1/Colorful_Azaleas_1.2_for_1.17-1.171.jar"
  concrete-plus = "https://www.brekitomasson.com/fettlol/mods/1.17.1/concrete-plus-1.9.jar"
  copper-beacons = "https://www.brekitomasson.com/fettlol/mods/1.17.1/copper-beacons-1.0.1.jar"
  copper-equipment = "https://www.brekitomasson.com/fettlol/mods/1.17.1/CopperEquipment-Fabric1.17.1-1.7.jar"
  croptopia = "^1.7.0-0.mpkg.1"
  cyanide = "https://www.brekitomasson.com/fettlol/mods/1.17.1/cyanide-fabric-1.17.1-1.2.3.jar"
  damagetilt = "^0.1.2-1.17.mpkg.1"
  dankstorage = "https://www.brekitomasson.com/fettlol/mods/1.17.1/dankstorage-2.2.1-1.17.1.jar"
  dark-loading-screen = "^1.6.7-0.mpkg.1"
  deepslate-cutting = "https://www.brekitomasson.com/fettlol/mods/1.17.1/deepslatecutting-1.2.2.jar"
  dense-ores = "https://www.brekitomasson.com/fettlol/mods/1.17.1/denseores-1.1+1.17.jar"
  discerning-furnace = "^1.0.3-0.mpkg.1"
  ducts = "https://www.brekitomasson.com/fettlol/mods/1.17.1/ducts-1.1.4.jar"
  dungeons-arise = "https://www.brekitomasson.com/fettlol/mods/1.17.1/DungeonsArise-1.17.1-2.1.48-fabric-beta.jar"
  dye-all-the-things = "https://www.brekitomasson.com/fettlol/mods/1.17.1/DyeAllTheThings-1.0.jar"
  earth2java = "^1.7.1-0.mpkg.1+1.17-pre3"
  eldritch-mobs = "^1.9.8-0.mpkg.1"
  emotecraft = "https://www.brekitomasson.com/fettlol/mods/1.17.1/emotecraft-for-MC1.17.1+1.18-2.1-SNAPSHOT-build.8-fabric.jar"
  enhanced-block-entities = "https://www.brekitomasson.com/fettlol/mods/1.17.1/enhancedblockentities-0.5+1.17.jar"
  extra-generators = "https://www.brekitomasson.com/fettlol/mods/1.17.1/extra-generators-1.1-BETA+1.17.jar"
  fabric = "*"
  fabric-language-kotlin = "^1.6.2-0.mpkg.3+kotlin.1.5.20"
  fallingleaves = "^1.7.3"
  fettlol-utilmod = "^1.2.7"
  flonters = "https://www.brekitomasson.com/fettlol/mods/1.17.1/Flonters-1.2.1+1.17.1.jar"
  geckolib = "^3.0.18-1.17.mpkg.1"
  goblin-traders = "https://www.brekitomasson.com/fettlol/mods/1.17.1/goblin-traders-1.4.0.jar"
  grizzly-bear-mob = "^1.2.0-1.17.mpkg.1"
  guardians-galore = "https://www.brekitomasson.com/fettlol/mods/1.17.1/GuardiansGalore-1.17.1-2.1.jar"
  horseinfo = "https://www.brekitomasson.com/fettlol/mods/1.17.1/hwyla-addon-horseinfo-0.3.0-1.17.jar"
  horsestatsvanilla = "https://www.brekitomasson.com/fettlol/mods/1.17.1/horse-stats-vanilla-4.1.8.jar"
  illuminations = "https://www.brekitomasson.com/fettlol/mods/1.17.1/illuminations-1.10.1.jar"
  infinitywaterbucket = "https://www.brekitomasson.com/fettlol/mods/1.17.1/infinity-water-bucket-1.4.1-mc1.17-fabric.jar"
  inventory-profiles = "https://www.brekitomasson.com/fettlol/mods/1.17.1/InventoryProfilesNext-fabric-1.17-1.1.8.jar"
  keepheadnames = "^1.3.0"
  krypton = "^0.1.4-0.mpkg.1"
  lambda-better-grass = "https://www.brekitomasson.com/fettlol/mods/1.17.1/lambdabettergrass-1.2.1+1.17.jar"
  lambdynamiclights = "https://www.brekitomasson.com/fettlol/mods/1.17.1/lambdynamiclights-2.0.2+1.17.jar"
  leaf-decay = "https://www.brekitomasson.com/fettlol/mods/1.17.1/leaf-decay-1.3.0-1.17.1.jar"
  lifts = "https://www.brekitomasson.com/fettlol/mods/1.17.1/lifts-1.3-BETA+1.17.jar"
  lightoverlay = "^6.0.0-1.mpkg.pre.1"
  lithium = "^0.7.5-0.mpkg.1"
  mcdunegeonsweapons = "https://www.brekitomasson.com/fettlol/mods/1.17.1/mcdw-3.5.6.jar"
  mcdungeonsarmors = "https://www.brekitomasson.com/fettlol/mods/1.17.1/mcda-1.8.1.jar"
  mcf-easyfeed = "^1.3.0-0.mpkg.1"
  midas-hunger = "https://www.brekitomasson.com/fettlol/mods/1.17.1/midas-hunger-1.4.1.jar"
  miskatonicmysteries = "https://www.brekitomasson.com/fettlol/mods/1.17.1/miskatonicmysteries-0.0.8.jar"
  modmenu = "https://www.brekitomasson.com/fettlol/mods/1.17.1/modmenu-2.0.12.jar"
  more-axolotl-variants = "https://www.brekitomasson.com/fettlol/mods/1.17.1/mavm-1.0.5.jar"
  more-banner-features = "https://www.brekitomasson.com/fettlol/mods/1.17.1/morebannerfeatures-1.1.2.jar"
  more-berries = "https://www.brekitomasson.com/fettlol/mods/1.17.1/moreberries-1.4.4.jar"
  more-block-bricks = "https://www.brekitomasson.com/fettlol/mods/1.17.1/moreblockbricks-1.3.1-mc-1.17.x.jar"
  more-geodes = "https://www.brekitomasson.com/fettlol/mods/1.17.1/more-geodes-1.0.5.jar"
  mostructures = "https://www.brekitomasson.com/fettlol/mods/1.17.1/mostructures-1.3.0-pre1-1.17.1-fabric.jar"
  mythic-mounts = "https://www.brekitomasson.com/fettlol/mods/1.17.1/mythic-mounts-1.17.1-3.0.jar"
  no-null-processors = "https://www.brekitomasson.com/fettlol/mods/1.17.1/no_null_processors_fabric-1.0.0+1.17.1.jar"
  not-enough-animations = "https://www.brekitomasson.com/fettlol/mods/1.17.1/notenoughanimations-1.3.3.jar"
  notenoughcrashes = "^4.0.0-0.mpkg.1"
  npcvariety = "https://www.brekitomasson.com/fettlol/mods/1.17.1/npc-variety-1.17.0-2.2.0.jar"
  okzoomer = "https://www.brekitomasson.com/fettlol/mods/1.17.1/okzoomer-5.0.0-beta.2+1.17.jar"
  patchouli = "^1.17.1-0.mpkg.1.55"
  perfectaccuracy = "^1.1.0"
  polymorph = "^0.0.14-1.17.mpkg.1"
  presence-footsteps = "https://www.brekitomasson.com/fettlol/mods/1.17.1/PresenceFootsteps-r31-1.17-rc1.jar"
  quick-shulker = "https://www.brekitomasson.com/fettlol/mods/1.17.1/quickshulker-1.2.2-1.17.jar"
  repurposed-structures = "^2.5.7-0.mpkg.1+1.17.1"
  reroll = "^1.3.0"
  rightclickharvest = "^1.5.0-0.mpkg.1"
  ringofattraction = "https://www.brekitomasson.com/fettlol/mods/1.17.1/RingOfAttraction-Fabric-1.17.1-1.1.15.jar"
  roughlyenoughitems = "^6.1.330-0.mpkg.1"
  rpgstats = "https://www.brekitomasson.com/fettlol/mods/1.17.1/rpgstats-4.2.2+1.17.1.jar"
  satin-api = "https://www.brekitomasson.com/fettlol/mods/1.17.1/satin-1.6.1.jar"
  scorch = "https://www.brekitomasson.com/fettlol/mods/1.17.1/scorch-1.2.0.jar"
  seasons = "https://www.brekitomasson.com/fettlol/mods/1.17.1/fabric-seasons-1.3.1-BETA+1.17.jar"
  servertick = "^1.5.0-0.mpkg.1"
  simpletransport = "https://www.brekitomasson.com/fettlol/mods/1.17.1/simpletransport-1.0.1-1.17.1.jar"
  simply-improved-terrain = "https://www.brekitomasson.com/fettlol/mods/1.17.1/SimplyImprovedTerrain-0.4.0.3-Fabric-1.17.jar"
  skin-layers = "https://www.brekitomasson.com/fettlol/mods/1.17.1/3dSkinLayers-Fabric-1.3.0.jar"
  skylib = "https://www.brekitomasson.com/fettlol/mods/1.17.1/skylorlib-1.0.5.jar"
  slimy-floor = "https://www.brekitomasson.com/fettlol/mods/1.17.1/slimyfloor-1.17.1-1.2.0.jar"
  spark = "https://www.brekitomasson.com/fettlol/mods/1.17.1/spark-fabric.jar"
  spawnermod = "https://www.brekitomasson.com/fettlol/mods/1.17.1/fabric-branders-spawnermod-1.17.1-1.1.2.jar"
  squirrels = "https://www.brekitomasson.com/fettlol/mods/1.17.1/squirrels-1.2.0-1.17.jar"
  starlight = "^1.0.0-0.mpkg.2"
  stickyhopper = "https://www.brekitomasson.com/fettlol/mods/1.17.1/stickyhopper-3.0a-1.17.1.jar"
  taxfreelevels = "^1.2.1"
  techreborn = "^5.0.10-0.mpkg.1+beta"
  the-graveyard = "https://www.brekitomasson.com/fettlol/mods/1.17.1/The_Graveyard_2.1_(FABRIC)_for_1.17-1.17.1.jar"
  tokenable-furnaces = "https://www.brekitomasson.com/fettlol/mods/1.17.1/tokenablefurnaces-1.1.4.jar"
  transliterationlib = "https://www.brekitomasson.com/fettlol/mods/1.17.1/TRansliterationLib-fabric-1.2.2-1.17.1.jar"
  traverse = "https://www.brekitomasson.com/fettlol/mods/1.17.1/traverse-4.0.0.jar"
  trinkets = "https://www.brekitomasson.com/fettlol/mods/1.17.1/trinkets-3.0.2.jar"
  truedarkness = "^1.6.74-0.mpkg.1"
  trumpet-skeleton = "https://www.brekitomasson.com/fettlol/mods/1.17.1/trumpet-skeleton-fabric-1.1.4.jar"
  untitledduckmod = "^0.3.0-0.mpkg.1"
  vanilla-degus = "https://www.brekitomasson.com/fettlol/mods/1.17.1/vanilla_degus-1.17.1-v1.2.4-fabric.jar"
  villagernames = "https://www.brekitomasson.com/fettlol/mods/1.17.1/villagernames-1.17.1-2.0.1.jar"
  vistas = "^1.4.4-0.mpkg.1"
  voicechat = "https://www.brekitomasson.com/fettlol/mods/1.17.1/voicechat-fabric-1.17.1-2.1.15.jar"
  waystones = "^2.2.2-0.mpkg.1"
  winged = "https://www.brekitomasson.com/fettlol/mods/1.17.1/winged-1.17.1-3.0.0.jar"
  wolveswitharmor = "https://www.brekitomasson.com/fettlol/mods/1.17.1/wolves-with-armor-1.6.1-1.17.1.jar"
  wthit = "^3.11.1-0.mpkg.1"
  xaeros-minimap = "https://www.brekitomasson.com/fettlol/mods/1.17.1/Xaeros_Minimap_21.22.2_Fabric_1.17.1.jar"
  xaeros-worldmap = "https://www.brekitomasson.com/fettlol/mods/1.17.1/XaerosWorldMap_1.18.3_Fabric_1.17.1.jar"
  your-options-shall-be-respected = "https://www.brekitomasson.com/fettlol/mods/1.17.1/yosbr-0.1.1.jar"

[dev]
