
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "modpack"
  name = "fettlol-beta"
  description = "The 1.19.2 beta branch of the Fettlol Modpack. Might not be stable."
  version = "2.0.6"
  platform = "fabric"
  license = "MIT"
  author = "Breki Tomasson <breki.tomasson@gmail.com>"

# These are global requirements
[requirements]
  minecraft = "1.19.2"
  fabricLoader = "^0.14.21"

[dependencies]
  addadd = "modrinth:addadd@V8k1wNbi"
  adorn = "modrinth:adorn@4Af8VkZs"
  advancements-debug = "modrinth:advancements-debug@oTJoSDPx"
  alternate-current = "modrinth:alternate-current@FkanfPQt"
  amecs = "modrinth:amecs@RcXP5WO3"
  animatica = "modrinth:animatica@rghK1s60"
  architectury-api = "modrinth:architectury-api@HoIJp48v"
  autotag = "modrinth:autotag@VoyNngbb"
  axesareweapons = "^1.7.0"
  bad-packets = "modrinth:badpackets@AifWRdyF"
  better-animals-plus = "https://brekitomasson.com/fettlol/mods/1.19/betteranimalsplus-1.19.2-11.0.10-fabric.jar"
  better-animations-collection = "modrinth:better-animations-collection@Gsjt5pf5"
  better-beds = "modrinth:better-beds@JB2PhlW1"
  better-f3 = "modrinth:betterf3@RbNy07Bx"
  better-ping-display = "modrinth:better-ping-display-fabric@DCWtLDt7"
  better-safe-bed = "modrinth:better-safe-bed@G0k0PLM8"
  biome-makeover = "modrinth:biome-makeover@9RkVvM3O"
  blast = "https://brekitomasson.com/fettlol/mods/1.19/blast-1.10.jar"
  botania = "modrinth:botania@T1wWMXnl"
  capes = "modrinth:capes@loGr3PwQ"
  charm = "modrinth:charm@nGnXDTky"
  charmonium = "modrinth:charmonium@qgncfSZo"
  chat-heads = "modrinth:chat-heads@ro03SDgE"
  chipped = "modrinth:chipped@UStkQaSp"
  cloth-config = "^8.2.88+mpkg.1"
  collective = "modrinth:collective@MTb34BGn"
  coloredslime = "^1.4.0"
  concrete-plus = "https://brekitomasson.com/fettlol/mods/1.19/pandamc_concreteplus-1.9.5.jar"
  cosmetic-armor = "modrinth:cosmetic-armor@vSPCrVPs"
  create-fabric = "modrinth:create-fabric@wKEEi1qX"
  croptopia = "^2.2.0+mpkg.1"
  ctm = "modrinth:ctm-refabricated@GhkzxV3G"
  cyanide = "modrinth:cyanide@A5lOFeVU"
  dank-storage = "https://brekitomasson.com/fettlol/mods/1.19/dankstorage-1.19.2-4.3.jar"
  dawn-api = "modrinth:dawn@YdQQ22Uv"
  deepslate-instamine = "modrinth:deepslate-instamine@nufK0cLt"
  deepslatecutting = "modrinth:deepslatecutting@FHSlU72M"
  dense-ores-refabricated = "modrinth:dense-ores-refabricated@VccXkFbe"
  discerning-furnace = "modrinth:discerning-furnace@IH8vI09k"
  distanthorizons = "modrinth:distanthorizons@yEUygWBv"
  doggo-mod-overhauled = "modrinth:doggo-mod-overhauled@PNBOG5sK"
  ducts = "https://brekitomasson.com/fettlol/mods/1.19/ducts-1.1.8.jar"
  dyeallthethings = "^1.3.0"
  dynamic-asset-generator = "modrinth:dynamic_asset_generator@jxYUybJA"
  dynamic-fps = "modrinth:dynamic-fps@g9FOSLTq"
  easierenchanting = "modrinth:easierenchanting@sOLkILaG"
  eating-animation = "modrinth:eating-animation@UulaTOZ0"
  emotecraft = "modrinth:emotecraft@pFGcytFI"
  enhanced-mob-spawners = "modrinth:enhanced-mob-spawners@ViepXqTP"
  entity-collision-fix = "modrinth:entity-collision-fps-fix@vXgwHjoS"
  excavated-variants = "modrinth:excavated_variants@eV2Ps3sL"
  expanded-storage = "modrinth:expanded-storage@thfTDvBM"
  fabric = "*"
  fabric-language-kotlin = "modrinth:fabric-language-kotlin@s10JMAtS"
  fabric-waystones = "modrinth:fwaystones@thT8mzll"
  fallingleaves = "^1.13.0"
  ferrite-core = "modrinth:ferrite-core@kwjHqfz7"
  fettlol-utilmod = "^1.7.6"
  fish-of-thieves = "modrinth:fish-of-thieves@nQ6qPHyR"
  geckolib = "modrinth:geckolib@ATPZfRS1"
  global-data-and-resourcepacks = "https://brekitomasson.com/fettlol/mods/1.19/global_packs-fabric-1.19.2-1.14.3.1_fabric.jar"
  glow-ink-plus = "modrinth:glow-ink-plus@Hd1OymjV"
  go-fish = "https://brekitomasson.com/fettlol/mods/1.19/go-fish-1.6.0-1.19.1.jar"
  horse-stats-vanilla = "modrinth:horsestatsvanilla@W1Cr0hgK"
  immersive-armors = "modrinth:immersive-armors@XnHpnpHJ"
  immersive-paintings = "modrinth:immersive-paintings@PH1KtmsM"
  indium = "modrinth:indium@yTfou6df"
  indypets = "^1.2.1+1.19"
  infinity-water-bucket = "modrinth:infinity-water-bucket@lgNyqwIG"
  inventory-profiles-next = "modrinth:inventory-profiles-next@k1Rt7UkC"
  iris = "modrinth:iris@W00rBT3R"
  jamlib = "modrinth:jamlib@vlsKDiFO"
  krypton = "modrinth:krypton@vx0mZa04"
  lambda-better-grass = "modrinth:lambdabettergrass@UWFTYBmq"
  lambdynamiclights = "modrinth:lambdynamiclights@YQkZSlfq"
  lazy-dfu = "modrinth:lazydfu@4SHylIO9"
  libipn = "modrinth:libipn@Tbvv0fRT"
  light-overlay = "modrinth:light-overlay@8MLUOCy0"
  lithium = "modrinth:lithium@m6sVgAi6"
  mavapi = "modrinth:mavapi@VBZ13Nzd"
  mcf-easyfeed = "https://brekitomasson.com/fettlol/mods/1.19/mcf-easyfeed-1.3.0-1.19.2.jar"
  midas-hunger = "modrinth:midas-hunger@puFDPpyn"
  midnight-lib = "modrinth:midnightlib@p0LjncVW"
  miskatonic-mysteries = "https://brekitomasson.com/fettlol/mods/1.19/miskatonicmysteries-0.1.7.jar"
  missing-wilds = "modrinth:missing-wilds@4cTlUzWV"
  mixintrace = "modrinth:mixintrace@LGYOH4RN"
  modmenu = "modrinth:modmenu@gSoPJyVn"
  more-axolotl-variants = "modrinth:mavm@a6uPZBX8"
  more-berries = "https://brekitomasson.com/fettlol/mods/1.19/moreberries-1.5.1.jar"
  more-mobs = "modrinth:more-mobs@aDgeBoVD"
  naturalist = "modrinth:naturalist@J96Y4WM3"
  no-chat-reports = "modrinth:no-chat-reports@YuX53PIA"
  not-enough-animations = "modrinth:not-enough-animations@KZmMUPjz"
  npc-variety = "https://brekitomasson.com/fettlol/mods/1.19/npc-variety-1.19.2-2.2.2.jar"
  overpowered-mending = "modrinth:overpoweredmending@eI71t1Xd"
  owo = "modrinth:owo-lib@yGLYmVnT"
  patchouli = "modrinth:patchouli@NorgAU8F"
  perfectaccuracy = "^1.2.0+1.19"
  philips-ruins = "modrinth:philips-ruins@5ZW3CrPA"
  polymorph = "modrinth:polymorph@7L5hC81R"
  porting-lib = "modrinth:porting_lib@C7bNYQn5"
  promenade = "modrinth:promenade@uZy48sdY"
  puzzleslib = "modrinth:puzzles-lib@hYKHLRZ3"
  repurposed-structures = "modrinth:repurposed-structures-fabric@3vxgVHLo"
  resourceful-lib = "modrinth:resourceful-lib@mxiPijSw"
  retraining = "modrinth:retraining@MlJ3ohJu"
  revelationary = "modrinth:revelationary@2d9fuEjc"
  rightclickharvest = "modrinth:rightclickharvest@YiwK4aDu"
  ring-of-attraction = "https://brekitomasson.com/fettlol/mods/1.19/RingOfAttraction-Fabric--1.19.2-1.3.14.jar"
  rmscore = "modrinth:rmscore@Pj3rvMce"
  roughly-enough-items = "modrinth:roughly-enough-items@pUXhM35r"
  rpgstats = "modrinth:rpgstats@6N8NcYZO"
  servercore = "modrinth:servercore@kzD8EGTS"
  sheep-consistency = "https://brekitomasson.com/fettlol/mods/1.19/sheepconsistency-1.0.4.jar"
  simple-voice-chat = "modrinth:simple-voice-chat@K95RbSbU"
  simply-swords = "modrinth:simply-swords@AY99tna8"
  skin-layers = "modrinth:3dskinlayers@JHapWF9O"
  slimy-floor = "https://brekitomasson.com/fettlol/mods/1.19/slimyfloor-1.19.1-1.2.5.jar"
  snowy-trees = "modrinth:snowy-trees@mCGcCMXb"
  sodium = "modrinth:sodium@rAfhHfow"
  sodium-extra = "modrinth:sodium-extra@MTxUvPFz"
  sodium-options = "modrinth:reeses-sodium-options@uCsFu5xs"
  spark = "modrinth:spark@XhFbpH8f"
  spectrum = "modrinth:spectrum@CXcpEjJx"
  starlight = "^1.1.1+mpkg.1"
  taxfreelevels = "^1.3.3"
  terrablender = "modrinth:terrablender@silo0xJT"
  terralith = "modrinth:terralith@2w1uZoRC"
  terrestria = "modrinth:terrestria@sCRQjLLk"
  texels-paintings = "modrinth:texels-paintings@vqi8IXS8"
  thorium = "modrinth:thorium@vntUAZDw"
  toms-storage = "modrinth:toms-storage@mI1bA7bA"
  traverse = "modrinth:traverse@xRKo6rF9"
  treeaxe = "https://brekitomasson.com/fettlol/mods/1.19/TreeAxe-Fabric-1.19.2-1.2.24.jar"
  trinkets = "modrinth:trinkets@OLwsMJv4"
  visuality = "modrinth:visuality@TrPcZLjs"
  wavey-capes = "modrinth:wavey-capes@FBoyebR2"
  winged = "https://brekitomasson.com/fettlol/mods/1.19/winged-1.19-3.3.0.jar"
  wired-redstone = "modrinth:wiredredstone@thwqrcKD"
  wthit = "modrinth:wthit@B1Z37WLi"
  wthit-plugins = "modrinth:wthit-plugins@gBbT8uN4"
  xaeros-minimap = "modrinth:xaeros-minimap@7GBpgdcp"
  xaeros-worldmap = "modrinth:xaeros-world-map@FX41W6zb"
  yacl = "modrinth:yacl@bIVYcRpm"
  yigd = "modrinth:yigd@RQ4Ma39V"
  yosbr = "modrinth:yosbr@KMOzdYko"
  zoomify = "modrinth:zoomify@f017okM4"

[dev]
