
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "modpack"
  name = "fettlol-beta"
  description = "The 1.19.2 beta branch of the Fettlol Modpack. Might not be stable."
  version = "2.0.12"
  platform = "fabric"
  license = "MIT"
  author = "Breki Tomasson <breki.tomasson@gmail.com>"

# These are global requirements
[requirements]
  minecraft = "1.19.2"
  fabricLoader = "^0.15.10"

[dependencies]
  addadd = "modrinth:addadd@V8k1wNbi"
  additional-structures = "modrinth:additional-structures@Kwzpj5Nk"
  adorn = "modrinth:adorn@4Af8VkZs"
  advancements-debug = "modrinth:advancements-debug@oTJoSDPx"
  alternate-current = "modrinth:alternate-current@FkanfPQt"
  amecs = "modrinth:amecs@RcXP5WO3"
  amplified-nether = "modrinth:amplified-nether@sB14azEN"
  animatica = "modrinth:animatica@rghK1s60"
  appleskin = "modrinth:appleskin@tpQpTIMn"
  architectury-api = "modrinth:architectury-api@cde9Su0w"
  autotag = "modrinth:autotag@VoyNngbb"
  axesareweapons = "^1.7.1"
  bad-packets = "modrinth:badpackets@7Y5NcPRW"
  bellsandwhistles = "modrinth:bellsandwhistles@aP2tFPwc"
  better-animals-plus = "https://brekitomasson.com/fettlol/mods/1.19/betteranimalsplus-1.19.2-11.0.10-fabric.jar"
  better-animations-collection = "modrinth:better-animations-collection@Gsjt5pf5"
  better-beds = "modrinth:better-beds@JB2PhlW1"
  better-f3 = "modrinth:betterf3@h7DgRLng"
  better-ping-display = "modrinth:better-ping-display-fabric@DCWtLDt7"
  better-safe-bed = "modrinth:better-safe-bed@G0k0PLM8"
  biome-makeover = "modrinth:biome-makeover@9RkVvM3O"
  blahaj-fabric = "modrinth:blahaj_fabric@rPlENxgf"
  botania = "modrinth:botania@T1wWMXnl"
  capes = "modrinth:capes@loGr3PwQ"
  charm = "modrinth:charm@nGnXDTky"
  charmonium = "modrinth:charmonium@qgncfSZo"
  chat-heads = "modrinth:chat-heads@XphnAL9J"
  chipped = "modrinth:chipped@UStkQaSp"
  cloth-config = "^8.2.88+mpkg.1"
  collective = "modrinth:collective@aWMkM9hL"
  coloredslime = "^1.4.0"
  colorful-azaleas = "modrinth:colorful-azaleas@HboP1Ba5"
  concrete-plus = "https://brekitomasson.com/fettlol/mods/1.19/pandamc_concreteplus-1.9.5.jar"
  cosmetic-armor = "modrinth:cosmetic-armor@vSPCrVPs"
  create-fabric = "modrinth:create-fabric@ylv5ppFs"
  create-steam-n-rails = "modrinth:create-steam-n-rails@G5xDUd4X"
  croptopia = "^2.2.0+mpkg.1"
  ctm = "modrinth:ctm-refabricated@GhkzxV3G"
  cyanide = "modrinth:cyanide@A5lOFeVU"
  dank-storage = "https://brekitomasson.com/fettlol/mods/1.19/dankstorage-1.19.2-4.3.jar"
  dawn-api = "modrinth:dawn@YdQQ22Uv"
  deepslate-instamine = "modrinth:deepslate-instamine@nufK0cLt"
  deepslatecutting = "modrinth:deepslatecutting@FHSlU72M"
  dense-ores-refabricated = "modrinth:dense-ores-refabricated@VccXkFbe"
  discerning-furnace = "modrinth:discerning-furnace@A1SuJChn"
  doggo-mod-overhauled = "modrinth:doggo-mod-overhauled@6zdAMXfK"
  ducts = "https://brekitomasson.com/fettlol/mods/1.19/ducts-1.1.8.jar"
  dyeallthethings = "^1.3.0"
  dynamic-asset-generator = "modrinth:dynamic_asset_generator@jxYUybJA"
  dynamic-fps = "modrinth:dynamic-fps@8qMOAA4B"
  easierenchanting = "modrinth:easierenchanting@sOLkILaG"
  eating-animation = "modrinth:eating-animation@UulaTOZ0"
  emotecraft = "modrinth:emotecraft@pFGcytFI"
  enhanced-mob-spawners = "modrinth:enhanced-mob-spawners@ViepXqTP"
  entity-collision-fix = "modrinth:entity-collision-fps-fix@vXgwHjoS"
  expanded-storage = "modrinth:expanded-storage@ESt2xfLy"
  fabric = "*"
  fabric-language-kotlin = "modrinth:fabric-language-kotlin@ZMokinzs"
  fabric-waystones = "modrinth:fwaystones@thT8mzll"
  fallingleaves = "^1.13.0"
  ferrite-core = "modrinth:ferrite-core@kwjHqfz7"
  fettlol-utilmod = "^1.8.4"
  forge-config-api-port = "modrinth:forge-config-api-port@3VCgXZ79"
  geckolib = "modrinth:geckolib@ATPZfRS1"
  globalpacks = "modrinth:globalpacks@Q67gzc2j"
  glow-ink-plus = "modrinth:glow-ink-plus@Hd1OymjV"
  go-fish = "https://brekitomasson.com/fettlol/mods/1.19/go-fish-1.6.0-1.19.1.jar"
  horse-stats-vanilla = "modrinth:horsestatsvanilla@W1Cr0hgK"
  immersive-armors = "modrinth:immersive-armors@XnHpnpHJ"
  immersive-paintings = "modrinth:immersive-paintings@sIfgYkdd"
  indium = "modrinth:indium@yTfou6df"
  indypets = "^1.3.4+1.19.2"
  infinity-water-bucket = "modrinth:infinity-water-bucket@lgNyqwIG"
  inventory-profiles-next = "modrinth:inventory-profiles-next@10OBZt6w"
  iris = "modrinth:iris@LgOJIpIS"
  jamlib = "modrinth:jamlib@vlsKDiFO"
  krypton = "modrinth:krypton@vx0mZa04"
  lambda-better-grass = "modrinth:lambdabettergrass@UWFTYBmq"
  lambdynamiclights = "modrinth:lambdynamiclights@YQkZSlfq"
  lazy-dfu = "modrinth:lazydfu@4SHylIO9"
  libipn = "modrinth:libipn@mM0sz712"
  light-overlay = "modrinth:light-overlay@8MLUOCy0"
  lil-wings = "modrinth:lil-wings@QWXIQJ1X"
  lithium = "modrinth:lithium@m6sVgAi6"
  mavapi = "modrinth:mavapi@VBZ13Nzd"
  mcf-easyfeed = "https://brekitomasson.com/fettlol/mods/1.19/mcf-easyfeed-1.3.0-1.19.2.jar"
  midas-hunger = "modrinth:midas-hunger@puFDPpyn"
  midnight-lib = "modrinth:midnightlib@p0LjncVW"
  missing-wilds = "modrinth:missing-wilds@4cTlUzWV"
  mixintrace = "modrinth:mixintrace@LGYOH4RN"
  mo-structures = "modrinth:mo-structures@l5IdZ68C"
  modmenu = "modrinth:modmenu@gSoPJyVn"
  more-axolotl-variants = "modrinth:mavm@a6uPZBX8"
  more-berries = "https://brekitomasson.com/fettlol/mods/1.19/moreberries-1.5.1.jar"
  naturalist = "modrinth:naturalist@sVtayqoK"
  no-chat-reports = "modrinth:no-chat-reports@YuX53PIA"
  not-enough-animations = "modrinth:not-enough-animations@I7zFLf9X"
  npc-variety = "https://brekitomasson.com/fettlol/mods/1.19/npc-variety-1.19.2-2.2.2.jar"
  overpowered-mending = "modrinth:overpoweredmending@eI71t1Xd"
  owo = "modrinth:owo-lib@yGLYmVnT"
  patchouli = "modrinth:patchouli@NorgAU8F"
  perfectaccuracy = "^1.3.0"
  philips-ruins = "modrinth:philips-ruins@LJXXN3s7"
  polymorph = "modrinth:polymorph@Mq4la1Hv"
  porting-lib = "modrinth:porting_lib@j23kpso7"
  promenade = "modrinth:promenade@uZy48sdY"
  puzzleslib = "modrinth:puzzles-lib@hYKHLRZ3"
  regions-unexplored = "modrinth:regions-unexplored@L5Ti8Ac3"
  repurposed-structures = "modrinth:repurposed-structures-fabric@bxc0tyY5"
  resourceful-lib = "modrinth:resourceful-lib@mxiPijSw"
  retraining = "modrinth:retraining@iV0eFMMp"
  revelationary = "modrinth:revelationary@2d9fuEjc"
  rightclickharvest = "modrinth:rightclickharvest@4UWabEWo"
  ring-of-attraction = "https://brekitomasson.com/fettlol/mods/1.19/RingOfAttraction-Fabric--1.19.2-1.3.14.jar"
  rmscore = "modrinth:rmscore@Pj3rvMce"
  roughly-enough-items = "modrinth:roughly-enough-items@pUXhM35r"
  rpgstats = "modrinth:rpgstats@6N8NcYZO"
  servercore = "modrinth:servercore@kzD8EGTS"
  sheep-consistency = "https://brekitomasson.com/fettlol/mods/1.19/sheepconsistency-1.0.4.jar"
  skin-layers = "modrinth:3dskinlayers@bJzktOtx"
  slimy-floor = "https://brekitomasson.com/fettlol/mods/1.19/slimyfloor-1.19.1-1.2.5.jar"
  sodium = "modrinth:sodium@rAfhHfow"
  sodium-extra = "modrinth:sodium-extra@MTxUvPFz"
  sodium-options = "modrinth:reeses-sodium-options@uCsFu5xs"
  spark = "modrinth:spark@XhFbpH8f"
  spectrum = "modrinth:spectrum@1CaI36f7"
  spirit = "modrinth:spirit@UqO4a3u8"
  starlight = "^1.1.1+mpkg.1"
  taxfreelevels = "^1.3.9"
  terrablender = "modrinth:terrablender@silo0xJT"
  terralith = "modrinth:terralith@FOe2l0tx"
  terrestria = "modrinth:terrestria@EI3kvVZ8"
  texels-paintings = "modrinth:texels-paintings@vqi8IXS8"
  thorium = "modrinth:thorium@vntUAZDw"
  time-in-a-bottle = "modrinth:time-in-a-bottle@Nb08LRYs"
  towns-and-towers = "modrinth:towns-and-towers@s7UXEluf"
  traverse = "modrinth:traverse@xRKo6rF9"
  treeaxe = "https://brekitomasson.com/fettlol/mods/1.19/TreeAxe-Fabric-1.19.2-1.2.24.jar"
  trinkets = "modrinth:trinkets@OLwsMJv4"
  visuality = "modrinth:visuality@TrPcZLjs"
  wavey-capes = "modrinth:wavey-capes@srXuisxO"
  wilder-wild = "https://github.com/Fourmisain/WilderWild/releases/download/2.0.6-mc1.19.2-fix/WilderWild-2.0.6-Fabric+1.19.2-fix.jar"
  winged = "https://brekitomasson.com/fettlol/mods/1.19/winged-1.19-3.3.0.jar"
  wired-redstone = "modrinth:wiredredstone@thwqrcKD"
  wthit = "modrinth:wthit@GQlBEY21"
  wthit-plugins = "modrinth:wthit-plugins@gBbT8uN4"
  xaeros-minimap = "modrinth:xaeros-minimap@sPZxEpDf"
  xaeros-worldmap = "modrinth:xaeros-world-map@AFdUAvnz"
  yacl = "modrinth:yacl@bIVYcRpm"
  yigd = "modrinth:yigd@RQ4Ma39V"
  yosbr = "modrinth:yosbr@KMOzdYko"
  zoomify = "modrinth:zoomify@f017okM4"

[dev]
