
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "modpack"
  name = "fettlol-beta"
  description = "The 1.18.1 beta branch of the Fettlol Modpack. Might not be stable."
  version = "1.0.76"
  platform = "fabric"
  license = "MIT"
  author = "Breki Tomasson <breki.tomasson@gmail.com>"

# These are global requirements
[requirements]
  minecraft = "1.18.1"
  fabricLoader = "^0.12.6"

[dependencies]
  additional-additions = "https://brekitomasson.com/fettlol/mods/1.18/AdditionalAdditions-3.0.1.jar"
  adorn = "^3.0.0-0.mpkg.1"
  alaska-nativecraft = "https://brekitomasson.com/fettlol/mods/1.18/alaskanativecraft-1.4.1.jar"
  appleskin = "^2.2.0-1.18.mpkg.1"
  applied-energistics = "https://brekitomasson.com/fettlol/mods/1.18/appliedenergistics2-10.0.0-beta.3.jar"
  architectury = "^3.2.57-0.mpkg.1"
  axesareweapons = "^1.5.1"
  bedspreads = "https://brekitomasson.com/fettlol/mods/1.18/bedspreads-fabric-1.5.0-1.18.jar"
  blur = "^2.4.1-0.mpkg.1"
  branders-spawnermod = "https://brekitomasson.com/fettlol/mods/1.18/fabric-branders-spawnermod-1.18-1.1.2.jar"
  caracal-mob = "^1.3.3-1.18.mpkg.1"
  chat-heads = "^0.5.1-0.mpkg.1"
  cloth-config = "^6.0.45-0.mpkg.1"
  coloredslime = "^1.3.1"
  copper-equipment = "https://brekitomasson.com/fettlol/mods/1.18/CopperEquipment-Fabric1.18.1-1.8.1-ChristmasEdition.jar"
  croptopia = "https://brekitomasson.com/fettlol/mods/1.18/Croptopia-1.18-FABRIC-1.8.0.jar"
  damagetilt = "^0.1.2-1.18.mpkg.1"
  dank-storage = "https://brekitomasson.com/fettlol/mods/1.18/dankstorage-3.1-1.18.1.jar"
  dark-loading-screen = "^1.6.5-0.mpkg.1"
  deepslate-cutting = "https://brekitomasson.com/fettlol/mods/1.18/deepslatecutting-1.18-1.3.0.jar"
  dense-ores = "https://brekitomasson.com/fettlol/mods/1.18/denseores-1.2+1.18.1.jar"
  ducts = "https://brekitomasson.com/fettlol/mods/1.18/ducts-1.1.5.jar"
  earth2java = "^1.7.4-0.mpkg.1+1.18"
  eldritch-mobs = "https://brekitomasson.com/fettlol/mods/1.18/eldritch-mobs-1.10.1.jar"
  extra-generators = "https://brekitomasson.com/fettlol/mods/1.18/extra-generators-1.1.1-BETA+1.18.jar"
  fabric = "*"
  fabric-language-kotlin = "https://brekitomasson.com/fettlol/mods/1.18/fabric-language-kotlin-1.7.1+kotlin.1.6.10.jar"
  fallingleaves = "^1.8.0"
  fettlol-utilmod = "^1.3.1"
  geckolib = "^3.0.22-1.18.mpkg.1"
  go-fish = "^1.4.1-0.mpkg.1"
  grizzlybear-mob = "https://brekitomasson.com/fettlol/mods/1.18/grizzlybear-1.18-1.2.2.jar"
  guardians-galore = "https://brekitomasson.com/fettlol/mods/1.18/GuardiansGalore-1.18-3.0.jar"
  horsestats-vanilla = "https://brekitomasson.com/fettlol/mods/1.18/horse-stats-vanilla-4.1.10.jar"
  hwyla-horseinfo = "https://brekitomasson.com/fettlol/mods/1.18/hwyla-addon-horseinfo-0.4.0-1.18.jar"
  indium = "^1.0.2-0.mpkg.1.alpha1+mc1.18"
  inventory-profiles = "https://brekitomasson.com/fettlol/mods/1.18/InventoryProfilesNext-fabric-1.18-1.2.3.jar"
  keepheadnames = "^1.4.0+1.18"
  krypton = "^0.1.5-0.mpkg.1"
  lifts = "^1.4.0-1.18.mpkg.1.BETA"
  lithium = "^0.7.7-0.mpkg.1"
  mcda = "https://brekitomasson.com/fettlol/mods/1.18/mcda-1.9.0.jar"
  mcdw = "https://brekitomasson.com/fettlol/mods/1.18/mcdw-4.0.1.jar"
  mcf-easyfeed = "^1.3.0-1.18.mpkg.1"
  modmenu = "^3.0.0-0.mpkg.1"
  more-axolotl-variants = "https://brekitomasson.com/fettlol/mods/1.18/mavm-fabric-1.18.1-1.0.7a.jar"
  mythic-mounts = "https://brekitomasson.com/fettlol/mods/1.18/mythic-mounts-3.0.jar"
  not-enough-animations = "https://brekitomasson.com/fettlol/mods/1.18/notenoughanimations-fabric-1.4.0-mc1.18-pre1.jar"
  notenoughcrashes = "^4.1.3-1.18.mpkg.2+1.18.1"
  npc-variety = "https://brekitomasson.com/fettlol/mods/1.18/npc-variety-1.18-2.2.1.jar"
  okzoomer = "^5.0.0-0.mpkg.1.beta.3"
  perfectaccuracy = "^1.2.0"
  repurposed-structures = "^3.1.12-0.mpkg.1+1.18.1"
  reroll = "^1.3.0"
  ring-of-attraction = "https://brekitomasson.com/fettlol/mods/1.18/RingOfAttraction-Fabric-1.18.0-1.2.16.jar"
  roughlyenoughitems = "^7.0.343-0.mpkg.1"
  rpg-stats = "https://brekitomasson.com/fettlol/mods/1.18/rpgstats-4.3.2+1.18.1.jar"
  simple-voice-chat = "https://brekitomasson.com/fettlol/mods/1.18/voicechat-fabric-1.18.1-2.1.28.jar"
  skin-layers = "https://brekitomasson.com/fettlol/mods/1.18/3dSkinLayers-Fabric-1.3.1.jar"
  slimy-floor = "https://brekitomasson.com/fettlol/mods/1.18/slimyfloor-1.18-1.2.2.jar"
  sodium = "^0.4.0-0.mpkg.1.alpha5+build.9"
  sodium-extra = "https://brekitomasson.com/fettlol/mods/1.18/sodium-extra-mc1.18-0.3.7.jar"
  spark = "https://brekitomasson.com/fettlol/mods/1.18/spark-fabric.jar"
  starlight = "^1.0.0-1.18.mpkg.1"
  taxfreelevels = "^1.2.1"
  techreborn = "^5.1.0-0.mpkg.1.beta.2"
  villager-names = "https://brekitomasson.com/fettlol/mods/1.18/villagernames-1.18-2.0.2.jar"
  waystones = "^2.4.0-0.mpkg.1"
  wolves-with-armor = "https://brekitomasson.com/fettlol/mods/1.18/wolves-with-armor-1.7.0-1.18.jar"
  wthit = "^4.3.0-0.mpkg.1"
  xaeros-minimap = "https://brekitomasson.com/fettlol/mods/1.18/Xaeros_Minimap_21.22.3_Fabric_1.18.jar"
  xaeros-worldmap = "https://brekitomasson.com/fettlol/mods/1.18/XaerosWorldMap_1.18.6_Fabric_1.18.jar"

[dev]
