
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "modpack"
  name = "fettlol-beta"
  description = "The 1.18.2 beta branch of the Fettlol Modpack. Might not be stable."
  version = "1.1.7"
  platform = "fabric"
  license = "MIT"
  author = "Breki Tomasson <breki.tomasson@gmail.com>"

# These are global requirements
[requirements]
  minecraft = "1.18.2"
  fabricLoader = "^0.13.3"

[dependencies]
  additional-additions = "https://cdn.modrinth.com/data/R4TvILfj/versions/4.0.0/AdditionalAdditions-4.0.0.jar"
  adorn = "https://cdn.modrinth.com/data/E6FUtRJh/versions/2.4.0-fabric/Adorn-3.4.0%2B1.18.2-fabric.jar"
  appleskin = "^2.2.0+1.18.mpkg.1"
  # applied-energistics2 = "https://cdn.modrinth.com/data/XxWD5pD3/versions/fabric-11.0.0/appliedenergistics2-11.0.0.jar"
  architectury = "https://brekitomasson.com/fettlol/mods/1.18/architectury-4.4.59.jar"
  axesareweapons = "^1.5.1"
  bad-packets = "https://cdn.modrinth.com/data/ftdbN0KK/versions/fabric-0.1.2/badpackets-fabric-0.1.2.jar"
  bedspreads = "https://brekitomasson.com/fettlol/mods/1.18/bedspreads-fabric-1.5.0-1.18.jar"
  better-beds = "https://cdn.modrinth.com/data/kKwy3HU9/versions/1.2.0/betterbeds-1.2.0.jar"
  better-f3 = "https://cdn.modrinth.com/data/8shC1gFX/versions/1.2.4/BetterF3-1.2.4-Fabric-1.18.2.jar"
  better-recipe-book = "https://cdn.modrinth.com/data/vWIaVOTE/versions/1.5.6-2/brb-1.18.2-fabric-1.5.6.jar"
  biome-makeover = "https://brekitomasson.com/fettlol/mods/1.18/biomemakeover-FABRIC-1.18.2-1.4.19.jar"
  blast = "https://brekitomasson.com/fettlol/mods/1.18/blast-1.8.5.jar"
  blur = "https://cdn.modrinth.com/data/NK39zBp2/versions/2.4.1/blur-2.4.1.jar"
  bobby = "https://cdn.modrinth.com/data/M08ruV16/versions/3.1.1/bobby-3.1.1.jar"
  charm = "https://cdn.modrinth.com/data/pOQTcQmj/versions/4.1.0/charm-fabric-1.18-4.1.0.jar"
  charmonium = "https://cdn.modrinth.com/data/bpii4Xsa/versions/4.0.0/charmonium-fabric-1.18-4.0.0.jar"
  chat-heads = "^0.5.1+mpkg.1"
  chipped = "https://brekitomasson.com/fettlol/mods/1.18/chipped-1.2.jar"
  cloth-config = "^6.1.48+mpkg.1"
  coloredslime = "^1.3.1"
  concrete-plus = "https://brekitomasson.com/fettlol/mods/1.18/pandamc_concreteplus-1.9.3.jar"
  copper-stuff = "https://cdn.modrinth.com/data/lpbVzEpa/versions/1.0.0/CopperStuff-1.18.2-1.0.0.1913186568.jar"
  croptopia = "^1.8.2+1.18.2.mpkg.1.git.ea908a5"
  cyanide = "https://brekitomasson.com/fettlol/mods/1.18/cyanide-fabric-1.18.2-2.1.0.jar"
  damagetilt = "^0.1.2+1.18.mpkg.1"
  dank-storage = "https://brekitomasson.com/fettlol/mods/1.18/dankstorage-1.18.2-3.7.jar"
  dark-loading-screen = "^1.6.5+mpkg.1"
  dawn-api = "https://cdn.modrinth.com/data/meZK2DCX/versions/3.3.0/dawn-3.3.0.jar"
  deepslate-cutting = "https://cdn.modrinth.com/data/IiuFShHs/versions/1.3.3/deepslatecutting-1.18.2-1.3.3.jar"
  dense-ores = "https://cdn.modrinth.com/data/mJq5ykOP/versions/1.2.2+1.18.2/denseores-1.2.2%2B1.18.2.jar"
  ducts = "https://brekitomasson.com/fettlol/mods/1.18/ducts-1.1.7.jar"
  dye-all-the-things = "https://brekitomasson.com/fettlol/mods/1.18/DyeAllTheThings-1.1.jar"
  dynamic-asset-generator = "https://cdn.modrinth.com/data/83pFEQVb/versions/0.6.0-fabric/dynamic_asset_generator-fabric-1.18.2-0.6.0.jar"
  eating-animation = "https://brekitomasson.com/fettlol/mods/1.18/eating-animation-1.2.jar"
  eldritch-mobs = "https://brekitomasson.com/fettlol/mods/1.18/eldritch-mobs-1.11.0.jar"
  emotecraft = "https://cdn.modrinth.com/data/pZ2wrerK/versions/2.1.3-SNAPSHOT-build.23-MC1.18.2-fabric/emotecraft-for-MC1.18.2-2.1.3-SNAPSHOT-build.23-fabric.jar"
  enhanced-mob-spawners = "https://cdn.modrinth.com/data/ZF0coYok/versions/1.1.2/fabric-branders-spawnermod-1.18.2-1.1.2.jar"
  excavated-variants = "https://cdn.modrinth.com/data/IZaMGxb0/versions/0.6.2-fabric/excavated_variants-fabric-1.18.2-0.6.2.jar"
  expanded-storage = "https://cdn.modrinth.com/data/psjeHi3j/versions/7.3.12+1.18.2-fabric/expandedstorage-7.3.12%2B1.18.2.jar"
  extra-generators = "https://cdn.modrinth.com/data/VXtwLg17/versions/1.2.1-BETA+1.18/extra-generators-1.2.1-BETA%2B1.18.jar"
  fabric = "*"
  fabric-capes = "https://brekitomasson.com/fettlol/mods/1.18/Capes-1.3.1+1.18.2.jar"
  fabric-language-kotlin = "https://cdn.modrinth.com/data/Ha28R6CL/versions/1.7.2+kotlin.1.6.20/fabric-language-kotlin-1.7.2%2Bkotlin.1.6.20.jar"
  fabric-seasons = "https://brekitomasson.com/fettlol/mods/1.18/fabric-seasons-1.4-BETA+1.18.jar"
  fallingleaves = "^1.11.1"
  feature-nbt-deadlock-be-gone = "https://cdn.modrinth.com/data/HMNV4z01/versions/1.0.1+1.18.1_fabric/feature_nbt_deadlock_be_gone_fabric-1.0.1+1.18.1.jar"
  ferrite-core = "https://cdn.modrinth.com/data/uXXizFIs/versions/4.2.1/ferritecore-4.2.1-fabric.jar"
  fettlol-utilmod = "^1.3.4"
  flonters = "https://cdn.modrinth.com/data/36iNFpQE/versions/1.3.1/Flonters-1.3.1%2B1.18.2.jar"
  geckolib = "^3.0.23+1.18.mpkg.1"
  global-datapacks = "https://cdn.modrinth.com/data/bRa9yz7E/versions/1.1/Global-Datapack.jar"
  grizzlybear-mob = "https://brekitomasson.com/fettlol/mods/1.18/grizzlybear-1.18-1.3.jar"
  horsestats-vanilla = "https://cdn.modrinth.com/data/l4qoXLzx/versions/4.1.10/horse-stats-vanilla-4.1.10.jar"
  immersive-portals = "https://cdn.modrinth.com/data/zJpHMkdD/versions/1.3.7-1.18.2/immersive-portals-1.3.7-mc1.18.2-fabric.jar"
  indium = "https://cdn.modrinth.com/data/Orvt0mRa/versions/1.0.3+mc1.18.2/indium-1.0.3%2Bmc1.18.2.jar"
  infinity-water-bucket = "https://cdn.modrinth.com/data/nNMXZUPi/versions/1.18.1-2.0.0/Infinity-Water-Bucket-Fabric-1.18.1-2.0.0.jar"
  inventory-profiles = "https://cdn.modrinth.com/data/O7RBXm3n/versions/fabric-1.18.2-1.3.7/InventoryProfilesNext-fabric-1.18.2-1.3.7.jar"
  iris = "https://cdn.modrinth.com/data/YL57xq9U/versions/1.18.x-v1.2.4/iris-mc1.18.2-1.2.4-build.38.jar"
  keepheadnames = "^1.5.1+1.18"
  lamb-dynamic-lights = "https://cdn.modrinth.com/data/yBW8D80W/versions/2.1.0+1.17/lambdynamiclights-2.1.0+1.17.jar"
  lambda-better-grass = "https://cdn.modrinth.com/data/2Uev7LdA/versions/1.2.3+1.18/lambdabettergrass-1.2.3%2B1.18.jar"
  lazy-dfu = "https://cdn.modrinth.com/data/hvFnDODi/versions/0.1.2/lazydfu-0.1.2.jar"
  light-overlay = "https://brekitomasson.com/fettlol/mods/1.18/light-overlay-6.0.5.jar"
  lithium = "https://cdn.modrinth.com/data/gvQqBUqZ/versions/mc1.18.2-0.7.9/lithium-fabric-mc1.18.2-0.7.9.jar"
  mcda = "https://brekitomasson.com/fettlol/mods/1.18/mcda-2.0.6.jar"
  mcdw = "https://brekitomasson.com/fettlol/mods/1.18/mcdw-4.3.2.jar"
  mcf-easyfeed = "^1.3.0+1.18.mpkg.1"
  midas-hunger = "https://cdn.modrinth.com/data/abF2tqnb/versions/2.1.0/midas-hunger-2.1.0%2B1.18.2.jar"
  mo-structures = "https://cdn.modrinth.com/data/PTGd6dWp/versions/1.4.2+1.18.2/mostructures-1.4.2%2B1.18.2.jar"
  modmenu = "https://cdn.modrinth.com/data/mOgUt4GM/versions/3.2.2/modmenu-3.2.2.jar"
  more-axolotl-variants = "https://brekitomasson.com/fettlol/mods/1.18/mavm-fabric-1.18.1-1.0.7a.jar"
  more-berries = "https://brekitomasson.com/fettlol/mods/1.18/moreberries-1.4.9.jar"
  ninjaphenix-container-lib = "https://cdn.modrinth.com/data/TIhTvPdy/versions/1.3.0+1.18-fabric/ninjaphenix-container-library-1.3.0%2B1.18-fabric.jar"
  not-enough-animations = "https://brekitomasson.com/fettlol/mods/1.18/notenoughanimations-fabric-1.5.0-mc1.18.2.jar"
  notenoughcrashes = "^4.1.3+1.18.mpkg.2"
  npc-variety = "https://brekitomasson.com/fettlol/mods/1.18/npc-variety-1.18-2.2.2.jar"
  overpowered-mending = "https://cdn.modrinth.com/data/DKzFWXbg/versions/1.18.2-2.4.1/OverpoweredMending-1.18.2-2.4.1.jar"
  perfectaccuracy = "^1.2.0"
  pleasant-pigeons = "https://cdn.modrinth.com/data/edKwsxB7/versions/1.3.0-1.18.2/pigeons-1.3.0-1.18.2-x.jar"
  polymorph = "https://brekitomasson.com/fettlol/mods/1.18/polymorph-fabric-0.0.19-1.18.1.jar"
  promenade = "https://cdn.modrinth.com/data/GuE5FpvB/versions/2.6.1/promenade-2.6.1.jar"
  repurposed-structures = "https://cdn.modrinth.com/data/muf0XoRe/versions/4.1.7+1.18.2/repurposed_structures_fabric-4.1.7%2B1.18.2.jar"
  reroll = "^1.2.1"
  retraining = "https://brekitomasson.com/fettlol/mods/1.18/Retraining-fabric-1.18.2-1.1.0.jar"
  right-click-harvest = "https://brekitomasson.com/fettlol/mods/1.18/rightclickharvest-2.0.3.jar"
  ring-of-attraction = "https://brekitomasson.com/fettlol/mods/1.18/RingOfAttraction-Fabric-1.18.2-1.2.24.jar"
  rpg-stats = "https://cdn.modrinth.com/data/8RtckdKf/versions/4.3.10/rpgstats-4.3.10%2B1.18.2.jar"
  sheep-consistency = "https://brekitomasson.com/fettlol/mods/1.18/sheepconsistency-1.0.4.jar"
  simple-voice-chat = "https://cdn.modrinth.com/data/9eGKb6K1/versions/fabric-1.18.2-2.2.42/voicechat-fabric-1.18.2-2.2.42.jar"
  skin-layers = "https://brekitomasson.com/fettlol/mods/1.18/3dskinlayers-fabric-1.4.4-mc1.18.2.jar"
  skylor-lib = "https://brekitomasson.com/fettlol/mods/1.18/skylorlib-1.3.34.jar"
  slimy-floor = "https://brekitomasson.com/fettlol/mods/1.18/slimyfloor-1.18.2-1.2.3.jar"
  sodium = "https://cdn.modrinth.com/data/AANobbMI/versions/mc1.18.2-0.4.1/sodium-fabric-mc1.18.2-0.4.1%2Bbuild.15.jar"
  sodium-extra = "https://cdn.modrinth.com/data/PtjYWJkn/versions/mc1.18.2-0.4.3/sodium-extra-mc1.18.2-0.4.3.jar"
  sodium-options = "https://cdn.modrinth.com/data/Bh37bMuy/versions/mc1.18.2-1.4.2/reeses_sodium_options-mc1.18.2-1.4.2.jar"
  spark = "https://cdn.modrinth.com/data/l6YH9Als/versions/1.9.1-fabric/spark-1.9.1-fabric.jar"
  starlight = "^1.0.1+mpkg.1"
  taxfreelevels = "^1.3.0"
  techreborn = "https://brekitomasson.com/fettlol/mods/1.18/TechReborn-5.2.0-beta.3.jar"
  terra-blender = "https://brekitomasson.com/fettlol/mods/1.18/TerraBlender-fabric-1.18.2-1.1.0.99.jar"
  thorium = "https://cdn.modrinth.com/data/ImUQFWcy/versions/1.2.1/thorium-1.2.1.jar"
  traverse = "https://cdn.modrinth.com/data/kXygSBVI/versions/5.0.0-alpha.2/traverse-5.0.0-alpha.2.jar"
  tree-axe = "https://brekitomasson.com/fettlol/mods/1.18/TreeAxe-Fabric-1.18.2-1.1.40.jar"
  vanilla-degus = "https://brekitomasson.com/fettlol/mods/1.18/vanilla_degus-1.18.2-v1.3.0-fabric.jar"
  villager-names = "https://brekitomasson.com/fettlol/mods/1.18/villagernames-1.18.2-4.0.3.jar"
  visuality = "https://cdn.modrinth.com/data/rI0hvYcd/versions/0.4.2/visuality-0.4.2.jar"
  waystones = "https://cdn.modrinth.com/data/sTZr7NVo/versions/2.5.0/wraith-waystones-2.5.0.jar"
  winged = "https://brekitomasson.com/fettlol/mods/1.18/winged-1.18.2-3.2.0.jar"
  wolves-with-armor = "https://brekitomasson.com/fettlol/mods/1.18/wolves-with-armor-1.7.1-1.18.2.jar"
  zoomify = "https://cdn.modrinth.com/data/w7ThoJFB/versions/1.4.0/Zoomify-1.4.0.jar"

[dev]
