
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "modpack"
  name = "fettlol-beta"
  description = "The 1.18.2 beta branch of the Fettlol Modpack. Might not be stable."
  version = "1.1.59"
  platform = "fabric"
  license = "MIT"
  author = "Breki Tomasson <breki.tomasson@gmail.com>"

# These are global requirements
[requirements]
  minecraft = "1.18.2"
  fabricLoader = "^0.14.9"

[dependencies]
  additional-additions = "modrinth:addadd@BeGqFDb2"
  adorn = "modrinth:adorn@6N5U8wzl"
  advancements-debug = "modrinth:advancements-debug@oTJoSDPx"
  alaska-nativecraft = "modrinth:alaska-native-craft@MRrmH8JB"
  alternate-current = "modrinth:alternate-current@gUosQHld"
  amecs = "modrinth:amecs@FlJ0SOQk"
  appleskin = "^2.2.0+1.18.mpkg.1"
  applied-energistics = "modrinth:ae2@MPdVG6oo"
  architectury = "modrinth:architectury-api@rJ54rLqX"
  axesareweapons = "^1.5.1"
  bad-packets = "modrinth:badpackets@vH59yR5Z"
  bedspreads = "^1.5.0+1.18.mpkg.1"
  better-animals-plus = "https://brekitomasson.com/fettlol/mods/1.18/betteranimalsplus-1.18.2-11.0.5-fabric.jar"
  better-enchanted-books = "modrinth:better-enchanted-books@Hv0PDVtx"
  better-f3 = "modrinth:betterf3@qUyRV6XT"
  better-ping-display = "modrinth:better-ping-display-fabric@D2bLU9Wv"
  better-recipe-book = "https://cdn.modrinth.com/data/vWIaVOTE/versions/1.5.6-2/brb-1.18.2-fabric-1.5.6.jar"
  better-safe-bed = "modrinth:better-safe-bed@E2Wn4d7E"
  biome-makeover = "modrinth:biome-makeover@cW94KePs"
  blast = "https://brekitomasson.com/fettlol/mods/1.18/blast-1.8.5.jar"
  blur = "^2.4.1+mpkg.1"
  bushier-flowers = "https://brekitomasson.com/fettlol/mods/1.18/bushierflowers-0.0.2-1.18.2.jar"
  capes = "modrinth:capes@IiXFyaYT"
  caracal-mod = "modrinth:caracal_mob@QW0FB8DZ"
  cats-expanded = "modrinth:cats-expanded@yceBXAqg"
  charm = "modrinth:charm@Lmye13jl"
  charmonium = "modrinth:charmonium@rzkLIRCX"
  chat-heads = "^0.5.1+mpkg.1"
  chipped = "https://brekitomasson.com/fettlol/mods/1.18/chipped-2.0.0-fabric.jar"
  cloth-config = "^6.1.48+mpkg.1"
  coloredslime = "^1.3.1"
  concrete-plus = "https://brekitomasson.com/fettlol/mods/1.18/pandamc_concreteplus-1.9.3.jar"
  copper-stuff = "modrinth:copperstuff@SCCOiPMD"
  cosmetic-armor = "modrinth:cosmetic-armor@nUZFo7BJ"
  create = "^0.5.0+mpkg.8.git.ddf8a326a"
  create-plus = "modrinth:createplus@9UJV0MUF"
  croptopia = "^1.8.2+1.18.2.mpkg.1.git.ea908a5"
  ctm = "https://brekitomasson.com/fettlol/mods/1.18/ctm-fabric-1.0.0+1.18.jar"
  cyanide = "https://brekitomasson.com/fettlol/mods/1.18/cyanide-fabric-1.18.2-2.1.0.jar"
  damagetilt = "^0.1.2+1.18.mpkg.1"
  dank-storage = "https://brekitomasson.com/fettlol/mods/1.18/dankstorage-1.18.2-3.9.jar"
  dawn-api = "modrinth:dawn@QAp3E5ko"
  deepslate-cutting = "modrinth:deepslatecutting@9GR6NzaH"
  dense-ores = "modrinth:dense-ores-refabricated@hbgC0Evh"
  discerning-furnace = "modrinth:discerning-furnace@ioEkTiNz"
  distant-horizons = "https://brekitomasson.com/fettlol/mods/1.18/DistantHorizons-1.6.5a-1.18.2.jar"
  ducts = "https://brekitomasson.com/fettlol/mods/1.18/ducts-1.1.7.jar"
  dyeallthethings = "^1.3.0"
  dynamic-asset-generator = "modrinth:dynamic_asset_generator@YCA8JXFR"
  dynamic-fps = "modrinth:dynamic-fps@LttnLLIj"
  earth2java = "modrinth:earth2java@CaBSGdlJ"
  eating-animation = "modrinth:eating-animation@Ok8kSWZQ"
  ellemes-container-lib = "https://cdn.modrinth.com/data/TIhTvPdy/versions/1.4.0-beta.1+fabric/ellemes-container-library-1.4.0-beta.1%2B1.18.2-fabric.jar"
  emotecraft = "modrinth:emotecraft@MjLxuS9U"
  enhanced-mob-spawners = "modrinth:enhanced-mob-spawners@7pmD6CHX"
  entity-collision-fix = "https://brekitomasson.com/fettlol/mods/1.18/Entity_Collision_FPS_Fix-fabric-1.18.2-1.0.0.jar"
  excavated-variants = "modrinth:excavated_variants@f1tuKqn5"
  expanded-storage = "https://cdn.modrinth.com/data/psjeHi3j/versions/7.4.0-beta.2+fabric/expandedstorage-7.4.0-beta.2%2B1.18.2-fabric.jar"
  extra-generators = "modrinth:extra-generators@8wkdIw8C"
  fabric = "*"
  fabric-language-kotlin = "modrinth:fabric-language-kotlin@yLIAMDzv"
  fabric-waystones = "modrinth:fwaystones@WR8srhYy"
  fallingleaves = "^1.11.1"
  feature-nbt-deadlock-be-gone = "^1.0.1+mpkg.1"
  ferrite-core = "https://cdn.modrinth.com/data/uXXizFIs/versions/4.2.1/ferritecore-4.2.1-fabric.jar"
  fettlol-utilmod = "^1.5.4"
  fish-of-thieves = "modrinth:fish-of-thieves@5cmv3RJO"
  flonters = "modrinth:flonters@QTK1mkXa"
  geckolib = "^3.0.23+1.18.mpkg.1"
  global-data-and-resourcepacks = "https://brekitomasson.com/fettlol/mods/1.18/global_packs-fabric-1.18.2-1.12.2.jar"
  go-fish = "https://brekitomasson.com/fettlol/mods/1.18/go-fish-1.5.0-1.18.2.jar"
  grizzlybear-mob = "modrinth:grizzly-bear@fMVgtrLc"
  horse-stats-vanilla = "modrinth:horsestatsvanilla@jfQfoNQx"
  indium = "modrinth:indium@H45YVREb"
  indypets = "^1.0.0"
  infinity-water-bucket = "https://cdn.modrinth.com/data/nNMXZUPi/versions/1.18.1-2.0.0/Infinity-Water-Bucket-Fabric-1.18.1-2.0.0.jar"
  inventory-profiles-next = "modrinth:inventory-profiles-next@BEa4OrkK"
  jamlib = "^0.0.5+mpkg.1"
  keepheadnames = "^1.5.1+1.18"
  krypton = "modrinth:krypton@vJQ7plH2"
  lambda-better-grass = "modrinth:lambdabettergrass@LpLEGUBZ"
  lambdynamiclights = "https://cdn.modrinth.com/data/yBW8D80W/versions/2.1.0%2B1.17/lambdynamiclights-2.1.0%2B1.17.jar"
  lazy-dfu = "modrinth:lazydfu@C6e265zK"
  libipn = "modrinth:libipn@Rl0p7f2w"
  light-overlay = "modrinth:light-overlay@f74N4LqG"
  lithium = "modrinth:lithium@pHl1Vi6k"
  mcf-easyfeed = "^1.3.0+1.18.mpkg.1"
  midashunger = "^2.1.0+mpkg.1.1.18.2"
  midnight-lib = "modrinth:midnightlib@CRaHmCcJ"
  minerslunchbox = "^1.0.1+mc1.18.2"
  miskatonic-mysteries = "https://brekitomasson.com/fettlol/mods/1.18/miskatonicmysteries-0.1.3.jar"
  missing-wilds = "modrinth:missing-wilds@UoZjeXyw"
  mob-farm-helpers = "https://brekitomasson.com/fettlol/mods/1.18/MobFarmHelpers-1.18.2-1.5.1.jar"
  modmenu = "modrinth:modmenu@d86kV6wd"
  more-axolotl-variants = "modrinth:mavm@V0DyIuBa"
  more-berries = "https://brekitomasson.com/fettlol/mods/1.18/moreberries-1.4.9.jar"
  mostructures = "modrinth:mo-structures@YcBteQIZ"
  naturalist = "https://brekitomasson.com/fettlol/mods/1.18/naturalist-fabric-1.1.1-1.18.2.jar"
  not-enough-animations = "modrinth:not-enough-animations@KTGfH3KC"
  notenoughcrashes = "^4.1.3+1.18.mpkg.2"
  npc-variety = "https://brekitomasson.com/fettlol/mods/1.18/npc-variety-1.18.2-2.2.1.jar"
  overpowered-mending = "modrinth:overpoweredmending@BGQzS6cB"
  owo = "modrinth:owo-lib@uAXx21D1"
  patchouli = "modrinth:patchouli@yLlzynQ5"
  perfectaccuracy = "^1.2.0"
  ping-me = "^1.0.0"
  polymorph = "^0.0.21+1.18.mpkg.1"
  promenade = "modrinth:promenade@6tKTgY0S"
  repurposed-structures = "modrinth:repurposed-structures-fabric@IgOLXw7Q"
  reroll = "^1.2.1"
  retraining = "modrinth:retraining@oT9IShs4"
  revelationary = "modrinth:revelationary@XVtjQuiL"
  rightclickharvest = "modrinth:rightclickharvest@Ht8H2Aow"
  ring-of-attraction = "https://brekitomasson.com/fettlol/mods/1.18/RingOfAttraction-Fabric-1.18.2-1.2.24.jar"
  roughly-enough-items = "modrinth:roughly-enough-items@18IUTNPN"
  roughlyenoughresources = "https://brekitomasson.com/fettlol/mods/1.18/rer-2.5.2.jar"
  rpgstats = "modrinth:rpgstats@MV29P2BO"
  servercore = "modrinth:servercore@1Axad5Jl"
  sheep-consistency = "https://brekitomasson.com/fettlol/mods/1.18/sheepconsistency-1.0.4.jar"
  simple-voice-chat = "modrinth:simple-voice-chat@rfrxsAs7"
  simply-swords = "modrinth:simply-swords@gWAEJxe2"
  skin-layers = "modrinth:3dskinlayers@SuL3Z1P0"
  slimy-floor = "https://brekitomasson.com/fettlol/mods/1.18/slimyfloor-1.18.2-1.2.3.jar"
  snowy-trees = "modrinth:snowy-trees@l8pn9mkd"
  sodium = "modrinth:sodium@74Y5Z8fo"
  sodium-extra = "modrinth:sodium-extra@2mn0qHfs"
  sodium-options = "modrinth:reeses-sodium-options@hl16W0ql"
  spark = "modrinth:spark@JjikdHMk"
  spectrum = "modrinth:spectrum@YFmcNhOm"
  starlight = "^1.0.1+mpkg.1"
  status = "modrinth:status@PlroDSu5"
  taxfreelevels = "^1.3.0"
  techreborn = "^5.2.0+mpkg.1"
  terrablender = "https://brekitomasson.com/fettlol/mods/1.18/TerraBlender-fabric-1.18.2-1.2.0.126.jar"
  terrestria = "modrinth:terrestria@7Ekn2RL2"
  thorium = "modrinth:thorium@DxVNym3k"
  traverse = "modrinth:traverse@tHcZW9xu"
  treeaxe = "https://brekitomasson.com/fettlol/mods/1.18/TreeAxe-Fabric-1.18.2-1.1.42.jar"
  trinkets = "modrinth:trinkets@XqLNMi9J"
  vanilla-degus = "https://brekitomasson.com/fettlol/mods/1.18/vanilla_degus-1.18.2-v1.3.0-fabric.jar"
  villagernames = "https://brekitomasson.com/fettlol/mods/1.18/villagernames-1.18.2-4.0.9.jar"
  visuality = "modrinth:visuality@cI5HA5nq"
  winged = "https://brekitomasson.com/fettlol/mods/1.18/winged-1.18.2-3.2.0.jar"
  wired-redstone = "modrinth:wiredredstone@MRAM4IyI"
  wolves-with-armor = "https://brekitomasson.com/fettlol/mods/1.18/wolves-with-armor-1.7.1-1.18.2.jar"
  xaeros-worldmap = "https://brekitomasson.com/fettlol/mods/1.18/XaerosWorldMap_1.26.1_Fabric_1.18.2.jar"
  yosbr = "modrinth:yosbr@dStXfyg3"
  zoomify = "modrinth:zoomify@sC6H3PnU"

[dev]
