
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "modpack"
  name = "fettlol-beta"
  description = "The 1.18.1 beta branch of the Fettlol Modpack. Might not be stable."
  version = "1.0.82"
  platform = "fabric"
  license = "MIT"
  author = "Breki Tomasson <breki.tomasson@gmail.com>"

# These are global requirements
[requirements]
  minecraft = "1.18.2"
  fabricLoader = "^0.13.3"

[dependencies]
  additional-additions = "https://cdn.modrinth.com/data/R4TvILfj/versions/3.0.1.1f/additionaladditions-3.0.1.1.jar"
  appleskin = "^2.2.0+1.18.mpkg.1"
  architectury = "https://brekitomasson.com/fettlol/mods/1.18/architectury-4.0.30.jar"
  axesareweapons = "^1.5.1"
  bedspreads = "https://brekitomasson.com/fettlol/mods/1.18/bedspreads-fabric-1.5.0-1.18.jar"
  blur = "https://cdn.modrinth.com/data/NK39zBp2/versions/2.4.1/blur-2.4.1.jar"
  chat-heads = "^0.5.1+mpkg.1"
  cloth-config = "^6.1.48+mpkg.1"
  coloredslime = "^1.3.1"
  concrete-plus = "https://brekitomasson.com/fettlol/mods/1.18/pandamc_concreteplus-1.9.3.jar"
  continuity = "https://cdn.modrinth.com/data/1IjD5062/versions/1.1.0+1.18.2/continuity-1.1.0%2B1.18.2.jar"
  copper-stuff = "https://cdn.modrinth.com/data/lpbVzEpa/versions/1.0.0/CopperStuff-1.18.2-1.0.0.1913186568.jar"
  damagetilt = "^0.1.2+1.18.mpkg.1"
  dank-storage = "https://brekitomasson.com/fettlol/mods/1.18/dankstorage-1.18.2-3.6.jar"
  dark-loading-screen = "^1.6.5+mpkg.1"
  deepslate-cutting = "https://cdn.modrinth.com/data/IiuFShHs/versions/1.3.2/deepslatecutting-1.18.2-1.3.2.jar"
  dense-ores = "https://cdn.modrinth.com/data/mJq5ykOP/versions/1.2.2+1.18.2/denseores-1.2.2%2B1.18.2.jar"
  dye-all-the-things = "https://brekitomasson.com/fettlol/mods/1.18/DyeAllTheThings-1.1.jar"
  earth2java = "https://cdn.modrinth.com/data/D2Q91keW/versions/1.8.0/Earth2Java-1.8.0%2B1.18.2.jar"
  eating-animation = "https://brekitomasson.com/fettlol/mods/1.18/eating-animation-1.2.jar"
  emotecraft = "https://cdn.modrinth.com/data/pZ2wrerK/versions/2.1-MC1.18.1-fabric/emotecraft-for-MC1.18.1-2.1-fabric.jar"
  enhanced-mob-spawners = "https://cdn.modrinth.com/data/ZF0coYok/versions/1.1.2/fabric-branders-spawnermod-1.18.2-1.1.2.jar"
  extra-generators = "https://cdn.modrinth.com/data/VXtwLg17/versions/1.1.1-BETA+1.18/extra-generators-1.1.1-BETA+1.18.jar"
  fabric = "*"
  fabric-language-kotlin = "https://cdn.modrinth.com/data/Ha28R6CL/versions/1.7.1+kotlin.1.6.10/fabric-language-kotlin-1.7.1+kotlin.1.6.10.jar"
  fabricated-chisel = "https://cdn.modrinth.com/data/4KWv7wbN/versions/1.4.5/chisel-1.4.5%2B1.18.2.jar"
  fallingleaves = "^1.9.0"
  feature-nbt-deadlock-be-gone = "https://cdn.modrinth.com/data/HMNV4z01/versions/1.0.1+1.18.1_fabric/feature_nbt_deadlock_be_gone_fabric-1.0.1+1.18.1.jar"
  fettlol-utilmod = "^1.3.4"
  flonters = "https://brekitomasson.com/fettlol/mods/1.18/Flonters-1.3.1+1.18.2.jar"
  geckolib = "^3.0.23+1.18.mpkg.1"
  grizzlybear-mob = "https://brekitomasson.com/fettlol/mods/1.18/grizzlybear-1.18-1.3.jar"
  horsestats-vanilla = "https://cdn.modrinth.com/data/l4qoXLzx/versions/4.1.10/horse-stats-vanilla-4.1.10.jar"
  indium = "https://cdn.modrinth.com/data/Orvt0mRa/versions/1.0.2+mc1.18.2/indium-1.0.2%2Bmc1.18.2.jar"
  infinity-water-bucket = "https://cdn.modrinth.com/data/nNMXZUPi/versions/1.18.1-2.0.0/Infinity-Water-Bucket-Fabric-1.18.1-2.0.0.jar"
  inventory-profiles = "https://cdn.modrinth.com/data/O7RBXm3n/versions/fabric-1.18.2-1.3.5/InventoryProfilesNext-fabric-1.18.2-1.3.5.jar"
  keepheadnames = "^1.5.1+1.18"
  lamb-dynamic-lights = "https://cdn.modrinth.com/data/yBW8D80W/versions/2.1.0+1.17/lambdynamiclights-2.1.0+1.17.jar"
  lambda-better-grass = "https://cdn.modrinth.com/data/2Uev7LdA/versions/1.2.3+1.18/lambdabettergrass-1.2.3%2B1.18.jar"
  lifts = "^1.4.0-BETA+1.18.mpkg.1"
  lithium = "https://brekitomasson.com/fettlol/mods/1.18/lithium-fabric-mc1.18.2-0.7.9.jar"
  mcda = "https://brekitomasson.com/fettlol/mods/1.18/mcda-2.0.3.jar"
  mcdw = "https://brekitomasson.com/fettlol/mods/1.18/mcdw-4.2.3.jar"
  mcf-easyfeed = "^1.3.0+1.18.mpkg.1"
  midas-hunger = "https://cdn.modrinth.com/data/abF2tqnb/versions/2.0.0+1.18.2/midas-hunger-2.0.0%2B1.18.2.jar"
  modmenu = "https://cdn.modrinth.com/data/mOgUt4GM/versions/3.1.0/modmenu-3.1.0.jar"
  more-axolotl-variants = "https://brekitomasson.com/fettlol/mods/1.18/mavm-fabric-1.18.1-1.0.7a.jar"
  not-enough-animations = "https://brekitomasson.com/fettlol/mods/1.18/notenoughanimations-fabric-1.4.0-mc1.18-pre1.jar"
  notenoughcrashes = "^4.1.3+1.18.mpkg.2"
  npc-variety = "https://brekitomasson.com/fettlol/mods/1.18/npc-variety-1.18-2.2.2.jar"
  perfectaccuracy = "^1.2.0"
  pleasant-pigeons = "https://cdn.modrinth.com/data/edKwsxB7/versions/1.2.0-1.18.2/pigeons-1.2.0.jar"
  polymorph = "https://brekitomasson.com/fettlol/mods/1.18/polymorph-fabric-0.0.19-1.18.1.jar"
  repurposed-structures = "https://cdn.modrinth.com/data/muf0XoRe/versions/4.0.2+1.18.2/repurposed_structures_fabric-4.0.2%2B1.18.2.jar"
  reroll = "^1.2.1"
  retraining = "https://brekitomasson.com/fettlol/mods/1.18/Retraining-fabric-1.18.2-1.1.0.jar"
  ring-of-attraction = "https://brekitomasson.com/fettlol/mods/1.18/RingOfAttraction-Fabric-1.18.1-1.2.20.jar"
  rpg-stats = "https://cdn.modrinth.com/data/8RtckdKf/versions/4.3.6/rpgstats-4.3.6%2B1.18.2.jar"
  sheep-consistency = "https://brekitomasson.com/fettlol/mods/1.18/sheepconsistency-1.0.4.jar"
  simple-voice-chat = "https://cdn.modrinth.com/data/9eGKb6K1/versions/fabric-1.18.2-2.2.27/voicechat-fabric-1.18.2-2.2.27.jar"
  skin-layers = "https://brekitomasson.com/fettlol/mods/1.18/3dskinlayers-fabric-1.4.2-mc1.18.2.jar"
  slimy-floor = "https://brekitomasson.com/fettlol/mods/1.18/slimyfloor-1.18.2-1.2.3.jar"
  sodium = "https://cdn.modrinth.com/data/AANobbMI/versions/mc1.18.2-0.4.1/sodium-fabric-mc1.18.2-0.4.1%2Bbuild.15.jar"
  sodium-extra = "https://cdn.modrinth.com/data/PtjYWJkn/versions/mc1.18.2-0.4.2/sodium-extra-mc1.18.2-0.4.2.jar"
  spark = "https://cdn.modrinth.com/data/l6YH9Als/versions/1.8.14-fabric/spark-1.8.14-fabric.jar"
  starlight = "^1.0.1+mpkg.1"
  taxfreelevels = "^1.3.0"
  techreborn = "https://brekitomasson.com/fettlol/mods/1.18/TechReborn-5.2.0-beta.2.jar"
  vanilla-degus = "https://brekitomasson.com/fettlol/mods/1.18/vanilla_degus-1.18.2-v1.3.0-fabric.jar"
  visuality = "https://cdn.modrinth.com/data/rI0hvYcd/versions/0.4.2/visuality-0.4.2.jar"
  winged = "https://brekitomasson.com/fettlol/mods/1.18/winged-1.18.2-3.2.0.jar"

[dev]
