
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "modpack"
  name = "fettlol-beta"
  description = "The 1.18.2 beta branch of the Fettlol Modpack. Might not be stable."
  version = "1.1.22"
  platform = "fabric"
  license = "MIT"
  author = "Breki Tomasson <breki.tomasson@gmail.com>"

# These are global requirements
[requirements]
  minecraft = "1.18.2"
  fabricLoader = "^0.14.7"

[dependencies]
  additional-additions = "https://cdn.modrinth.com/data/R4TvILfj/versions/4.0.5/AdditionalAdditions-4.0.5.jar"
  adorn = "https://cdn.modrinth.com/data/E6FUtRJh/versions/3.5.0-fabric/Adorn-3.5.0%2B1.18.2-fabric.jar"
  advancements-debug = "https://cdn.modrinth.com/data/rxMTwxyO/versions/2.3.0/advdebug-2.3.0.jar"
  alaska-nativecraft = "https://cdn.modrinth.com/data/iFnEtHsI/versions/1.4.4/alaskanativecraft-1.4.4.jar"
  amecs = "https://cdn.modrinth.com/data/rcLriA4v/versions/1.3.8+mc.1.18.2/amecs-1.3.8%2Bmc.1.18.2.jar"
  appleskin = "^2.2.0+1.18.mpkg.1"
  applied-energistics = "https://cdn.modrinth.com/data/XxWD5pD3/versions/fabric-11.1.3/appliedenergistics2-11.1.3.jar"
  architectury = "https://cdn.modrinth.com/data/lhGA9TYQ/versions/4.5.76+fabric/architectury-4.5.76-fabric.jar"
  axesareweapons = "^1.5.1"
  bad-packets = "https://cdn.modrinth.com/data/ftdbN0KK/versions/fabric-0.1.2/badpackets-fabric-0.1.2.jar"
  bedspreads = "^1.5.0+1.18.mpkg.1"
  better-animals-plus = "https://brekitomasson.com/fettlol/mods/1.18/betteranimalsplus-1.18.2-11.0.5-fabric.jar"
  better-enchanted-books = "https://cdn.modrinth.com/data/yjpXhps7/versions/1.3.1/better-enchanted-books-1.18.2-1.3.1.jar"
  better-f3 = "https://cdn.modrinth.com/data/8shC1gFX/versions/1.2.5.1/BetterF3-1.2.5-Fabric-1.18.2.jar"
  better-recipe-book = "https://cdn.modrinth.com/data/vWIaVOTE/versions/1.5.6-2/brb-1.18.2-fabric-1.5.6.jar"
  better-safe-bed = "https://cdn.modrinth.com/data/aUp4r9hY/versions/bettersafebed-1.18-fabric-a/bettersafebed-1.18-fabric-a.jar"
  biome-makeover = "https://cdn.modrinth.com/data/jG8Q2YwT/versions/fabric-1.18.2-1.4.26/biomemakeover-FABRIC-1.18.2-1.4.26.jar"
  blast = "https://brekitomasson.com/fettlol/mods/1.18/blast-1.8.5.jar"
  blur = "https://cdn.modrinth.com/data/NK39zBp2/versions/2.4.1/blur-2.4.1.jar"
  bobby = "https://cdn.modrinth.com/data/M08ruV16/versions/3.1.1/bobby-3.1.1.jar"
  capes = "https://cdn.modrinth.com/data/89Wsn8GD/versions/1.3.1+1.18.2/Capes-1.3.1%2B1.18.2.jar"
  caracal-mod = "https://cdn.modrinth.com/data/mLNfkt6W/versions/1.18.2-1.3.8/caracal-1.18.2-1.3.8.jar"
  charm = "https://cdn.modrinth.com/data/pOQTcQmj/versions/4.1.1/charm-fabric-1.18.2-4.1.1.jar"
  charmonium = "https://cdn.modrinth.com/data/bpii4Xsa/versions/4.1.0+1.18.2/charmonium-fabric-1.18.2-4.1.0.jar"
  chat-heads = "^0.5.1+mpkg.1"
  chipped = "https://brekitomasson.com/fettlol/mods/1.18/chipped-1.2.jar"
  cloth-config = "^6.1.48+mpkg.1"
  coloredslime = "^1.3.1"
  concrete-plus = "https://brekitomasson.com/fettlol/mods/1.18/pandamc_concreteplus-1.9.3.jar"
  copper-stuff = "https://cdn.modrinth.com/data/lpbVzEpa/versions/1.0.0/CopperStuff-1.18.2-1.0.0.1913186568.jar"
  create = "https://cdn.modrinth.com/data/Xbc0uyRg/versions/mc1.18.2_v0.4.1+637/create-mc1.18.2_v0.4.1%2B637.jar"
  create-plus = "https://cdn.modrinth.com/data/svgZx0UN/versions/1.0-beta4/createplus-1.0.0-beta4.jar"
  croptopia = "^1.8.2+1.18.2.mpkg.1.git.ea908a5"
  cyanide = "https://brekitomasson.com/fettlol/mods/1.18/cyanide-fabric-1.18.2-2.1.0.jar"
  damagetilt = "^0.1.2+1.18.mpkg.1"
  dank-storage = "https://brekitomasson.com/fettlol/mods/1.18/dankstorage-1.18.2-3.7.jar"
  dark-loading-screen = "^1.6.5+mpkg.1"
  dawn-api = "https://cdn.modrinth.com/data/meZK2DCX/versions/3.3.2/dawn-3.3.2.jar"
  deepslate-cutting = "https://cdn.modrinth.com/data/IiuFShHs/versions/1.3.4/deepslatecutting-1.18.2-1.3.4.jar"
  dense-ores = "https://cdn.modrinth.com/data/mJq5ykOP/versions/1.2.2+1.18.2/denseores-1.2.2%2B1.18.2.jar"
  discerning-furnace = "https://cdn.modrinth.com/data/G3Nz6HN4/versions/1.0.6+MC1.18-1.18.2/discerning-furnace-1.0.6%2BMC1.18-1.18.2.jar"
  ducts = "https://brekitomasson.com/fettlol/mods/1.18/ducts-1.1.7.jar"
  dyeallthethings = "^1.2.1"
  dynamic-asset-generator = "https://cdn.modrinth.com/data/83pFEQVb/versions/0.6.1-fabric/dynamic_asset_generator-fabric-1.18.2-0.6.1.jar"
  earth2java = "https://cdn.modrinth.com/data/D2Q91keW/versions/1.8.0/Earth2Java-1.8.0%2B1.18.2.jar"
  eating-animation = "https://cdn.modrinth.com/data/rUgZvGzi/versions/1.8/eating-animation-1.8.jar"
  ellemes-container-lib = "https://cdn.modrinth.com/data/TIhTvPdy/versions/1.4.0-beta.1+fabric/ellemes-container-library-1.4.0-beta.1%2B1.18.2-fabric.jar"
  emotecraft = "https://cdn.modrinth.com/data/pZ2wrerK/versions/2.1.3-SNAPSHOT-build.32-MC1.18.2-fabric/emotecraft-for-MC1.18.2-2.1.3-SNAPSHOT-build.32-fabric.jar"
  enhanced-mob-spawners = "https://cdn.modrinth.com/data/ZF0coYok/versions/1.1.2/fabric-branders-spawnermod-1.18.2-1.1.2.jar"
  entity-collision-fix = "https://brekitomasson.com/fettlol/mods/1.18/Entity_Collision_FPS_Fix-fabric-1.18.2-1.0.0.jar"
  excavated-variants = "https://cdn.modrinth.com/data/IZaMGxb0/versions/0.6.2-fabric/excavated_variants-fabric-1.18.2-0.6.2.jar"
  expanded-storage = "https://cdn.modrinth.com/data/psjeHi3j/versions/7.4.0-beta.2+fabric/expandedstorage-7.4.0-beta.2%2B1.18.2-fabric.jar"
  extra-generators = "https://cdn.modrinth.com/data/VXtwLg17/versions/1.2.1-BETA+1.18/extra-generators-1.2.1-BETA%2B1.18.jar"
  fabric = "*"
  fabric-language-kotlin = "https://cdn.modrinth.com/data/Ha28R6CL/versions/1.7.2+kotlin.1.6.20/fabric-language-kotlin-1.7.2%2Bkotlin.1.6.20.jar"
  fabric-waystones = "https://cdn.modrinth.com/data/sTZr7NVo/versions/2.5.4/wraith-waystones-2.5.4.jar"
  fallingleaves = "^1.11.1"
  feature-nbt-deadlock-be-gone = "^1.0.1+mpkg.1"
  ferrite-core = "https://cdn.modrinth.com/data/uXXizFIs/versions/4.2.1/ferritecore-4.2.1-fabric.jar"
  fettlol-utilmod = "^1.4.0"
  fish-of-thieves = "https://cdn.modrinth.com/data/BzOTnuqM/versions/1.0.7-fabric/fish_of_thieves-mc1.18.2-v1.0.7-fabric.jar"
  flonters = "https://cdn.modrinth.com/data/36iNFpQE/versions/1.3.1/Flonters-1.3.1%2B1.18.2.jar"
  geckolib = "^3.0.23+1.18.mpkg.1"
  global-data-and-resourcepacks = "https://brekitomasson.com/fettlol/mods/1.18/global_packs-fabric-1.18.2-1.12.2.jar"
  grizzlybear-mob = "https://cdn.modrinth.com/data/x6nc2i5M/versions/1.18.2-1.3/grizzlybear-1.18-1.3.jar"
  horsestatsvanilla = "https://cdn.modrinth.com/data/l4qoXLzx/versions/4.1.10/horse-stats-vanilla-4.1.10.jar"
  indium = "https://cdn.modrinth.com/data/Orvt0mRa/versions/1.0.6+mc1.18.2/indium-1.0.6%2Bmc1.18.2.jar"
  infinity-water-bucket = "https://cdn.modrinth.com/data/nNMXZUPi/versions/1.18.1-2.0.0/Infinity-Water-Bucket-Fabric-1.18.1-2.0.0.jar"
  inventory-profiles-next = "https://cdn.modrinth.com/data/O7RBXm3n/versions/fabric-1.18.2-1.5.3/InventoryProfilesNext-fabric-1.18.2-1.5.3.jar"
  iris = "https://cdn.modrinth.com/data/YL57xq9U/versions/1.18.x-v1.2.5/iris-mc1.18.2-1.2.5.jar"
  jamlib = "^0.0.5+mpkg.1"
  keepheadnames = "^1.5.1+1.18"
  lambda-better-grass = "https://cdn.modrinth.com/data/2Uev7LdA/versions/1.2.4+1.18/lambdabettergrass-1.2.4%2B1.18.jar"
  lambdynamiclights = "https://cdn.modrinth.com/data/yBW8D80W/versions/2.1.0+1.17/lambdynamiclights-2.1.0+1.17.jar"
  lazy-dfu = "https://cdn.modrinth.com/data/hvFnDODi/versions/0.1.2/lazydfu-0.1.2.jar"
  light-overlay = "https://cdn.modrinth.com/data/YfOlc91N/versions/6.0.5/light-overlay-6.0.5.jar"
  lithium = "https://cdn.modrinth.com/data/gvQqBUqZ/versions/mc1.18.2-0.7.10/lithium-fabric-mc1.18.2-0.7.10.jar"
  mcda = "https://brekitomasson.com/fettlol/mods/1.18/mcda-2.0.6.jar"
  mcdw = "https://brekitomasson.com/fettlol/mods/1.18/mcdw-4.4.0.jar"
  mcf-easyfeed = "^1.3.0+1.18.mpkg.1"
  midas-hunger = "https://cdn.modrinth.com/data/abF2tqnb/versions/2.1.0/midas-hunger-2.1.0%2B1.18.2.jar"
  midnight-lib = "https://cdn.modrinth.com/data/codAaoxh/versions/0.4.4/midnightlib-0.4.4.jar"
  mob-farm-helpers = "https://brekitomasson.com/fettlol/mods/1.18/MobFarmHelpers-1.18.2-1.5.1.jar"
  modmenu = "https://cdn.modrinth.com/data/mOgUt4GM/versions/3.2.2/modmenu-3.2.2.jar"
  more-axolotl-variants = "https://cdn.modrinth.com/data/zitu8weW/versions/1.0.8a/mavm-mc1.19-fabric-1.0.8a.jar"
  more-berries = "https://brekitomasson.com/fettlol/mods/1.18/moreberries-1.4.9.jar"
  mostructures = "https://cdn.modrinth.com/data/PTGd6dWp/versions/1.4.2+1.18.2/mostructures-1.4.2%2B1.18.2.jar"
  not-enough-animations = "https://cdn.modrinth.com/data/MPCX6s5C/versions/1.6.0-fabric-1.18/notenoughanimations-fabric-1.6.0-mc1.18.2.jar"
  notenoughcrashes = "^4.1.3+1.18.mpkg.2"
  npc-variety = "https://brekitomasson.com/fettlol/mods/1.18/npc-variety-1.18.2-2.2.1.jar"
  ottercraft = "https://brekitomasson.com/fettlol/mods/1.18/Ottercraft-fabric-1.1.12.jar"
  overpowered-mending = "https://cdn.modrinth.com/data/DKzFWXbg/versions/1.18.2-2.4.1/OverpoweredMending-1.18.2-2.4.1.jar"
  owo = "https://cdn.modrinth.com/data/ccKDOlHs/versions/0.7.2-no-cme+1.18/owo-lib-0.7.2-no-cme%2B1.18.jar"
  patchouli = "https://cdn.modrinth.com/data/nU0bVIaL/versions/1.18.2-71.1-fabric/Patchouli-1.18.2-71.1-FABRIC.jar"
  perfectaccuracy = "^1.2.0"
  polymorph = "^0.0.21+1.18.mpkg.1"
  promenade = "https://cdn.modrinth.com/data/GuE5FpvB/versions/2.6.3/promenade-2.6.3.jar"
  repurposed-structures = "https://cdn.modrinth.com/data/muf0XoRe/versions/4.1.14+1.18.2/repurposed_structures_fabric-4.1.14%2B1.18.2.jar"
  reroll = "^1.2.1"
  retraining = "https://cdn.modrinth.com/data/Iugiwphr/versions/1.1.0.3/Retraining-fabric-1.18.2-1.1.0.jar"
  rightclickharvest = "^2.1.1+0.mpkg.1"
  ring-of-attraction = "https://brekitomasson.com/fettlol/mods/1.18/RingOfAttraction-Fabric-1.18.2-1.2.24.jar"
  rpgstats = "https://cdn.modrinth.com/data/8RtckdKf/versions/4.3.12/rpgstats-4.3.12%2B1.18.2.jar"
  sheep-consistency = "https://brekitomasson.com/fettlol/mods/1.18/sheepconsistency-1.0.4.jar"
  simple-voice-chat = "https://cdn.modrinth.com/data/9eGKb6K1/versions/fabric-1.18.2-2.2.47/voicechat-fabric-1.18.2-2.2.47.jar"
  skin-layers = "https://cdn.modrinth.com/data/zV5r3pPn/versions/1.4.6-fabric-1.18/3dskinlayers-fabric-1.4.6-mc1.18.2.jar"
  slimy-floor = "https://brekitomasson.com/fettlol/mods/1.18/slimyfloor-1.18.2-1.2.3.jar"
  snowy-trees = "https://cdn.modrinth.com/data/QRtuy06g/versions/1.1.0/snowy-trees-1.1.0.jar"
  sodium = "https://cdn.modrinth.com/data/AANobbMI/versions/mc1.18.2-0.4.1/sodium-fabric-mc1.18.2-0.4.1%2Bbuild.15.jar"
  sodium-extra = "https://cdn.modrinth.com/data/PtjYWJkn/versions/mc1.18.2-0.4.3/sodium-extra-mc1.18.2-0.4.3.jar"
  sodium-options = "https://cdn.modrinth.com/data/Bh37bMuy/versions/mc1.18.2-1.4.2/reeses_sodium_options-mc1.18.2-1.4.2.jar"
  spark = "https://cdn.modrinth.com/data/l6YH9Als/versions/1.9.11-fabric/spark-1.9.11-fabric.jar"
  spectrum = "https://cdn.modrinth.com/data/3rc31Hgo/versions/1.4.2/spectrum-1.4.2-1.18.2-chaos_and_exploration.jar"
  starlight = "^1.0.1+mpkg.1"
  taxfreelevels = "^1.3.0"
  techreborn = "https://brekitomasson.com/fettlol/mods/1.18/TechReborn-5.2.0.jar"
  terrablender = "https://brekitomasson.com/fettlol/mods/1.18/TerraBlender-fabric-1.18.2-1.1.0.102.jar"
  thorium = "https://cdn.modrinth.com/data/ImUQFWcy/versions/1.2.1/thorium-1.2.1.jar"
  traverse = "https://cdn.modrinth.com/data/kXygSBVI/versions/5.1.0-beta/traverse-5.1.0-beta.jar"
  treeaxe = "https://brekitomasson.com/fettlol/mods/1.18/TreeAxe-Fabric-1.18.2-1.1.40.jar"
  trinkets = "https://cdn.modrinth.com/data/5aaWibi9/versions/3.3.1/trinkets-3.3.1.jar"
  vanilla-degus = "https://brekitomasson.com/fettlol/mods/1.18/vanilla_degus-1.18.2-v1.3.0-fabric.jar"
  villagernames = "https://brekitomasson.com/fettlol/mods/1.18/villagernames-1.18.2-4.0.3.jar"
  visuality = "https://cdn.modrinth.com/data/rI0hvYcd/versions/0.4.2/visuality-0.4.2.jar"
  winged = "https://brekitomasson.com/fettlol/mods/1.18/winged-1.18.2-3.2.0.jar"
  wolves-with-armor = "https://brekitomasson.com/fettlol/mods/1.18/wolves-with-armor-1.7.1-1.18.2.jar"
  yosbr = "https://cdn.modrinth.com/data/WwbubTsV/versions/0.1.1/yosbr-0.1.1.jar"
  zoomify = "https://cdn.modrinth.com/data/w7ThoJFB/versions/1.4.0/Zoomify-1.4.0.jar"

[dev]
