name: minepkg publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Publish release on minepkg.io
        uses: minepkg/action-publish@main
        with:
          api-key: ${{secrets.MINEPKG}}
